!< Reusable option sets: copy_options (issue #125, step 3.7; #77 4.1, T4.1-T4.11; D14).
program flap_test_copy_options
!< Reusable option sets: copy_options (issue #125, step 3.7; #77 4.1, T4.1-T4.11; D14).
!<
!< The named options of a group are copied by value into another group: every definition (help, action, default, nargs,
!< choices, envvar, hidden, negation, range, map, path checks, ...) and none of the runtime state; each copy has its own
!< value. Builtins are never copied. An envvar generated by auto_envvar_prefix is generated again for the target group; an
!< explicit one is copied verbatim. Every get has its own variable (nvfortran, B33).
use flap, only : command_line_interface, ERROR_COPY_POSITIONAL, ERROR_GROUP_CONSISTENCY, ERROR_M_EXCLUDE, ERROR_MISSING_CLA, &
                 ERROR_MISSING_GROUP, ERROR_MISSING_REQUIRED, ERROR_OUT_OF_RANGE
use flap_test_utils, only : assert, assert_contains, assert_equal, capture_close, capture_open, read_back
use penf, only : I4P

implicit none
type(command_line_interface) :: cli   !< Command Line Interface (CLI).
character(:), allocatable    :: out   !< Captured output.
character(:), allocatable    :: top   !< Option block of the top level.
character(:), allocatable    :: cmd   !< Option block of a command.
character(99)                :: s     !< Character value (every get before its check).
integer(I4P)                 :: lun   !< Capture unit.
integer(I4P)                 :: error !< Error trapping flag.
integer(I4P)                 :: i4    !< Integer value.
logical                      :: v     !< Flag value.

call capture_open(lun)
! T4.1, T4.3: every command parses its copy, with its own value
call run('compile -j 4 --verbose')
i4 = jobs_of_compile(error)
call assert(i4 == 4 .and. error == 0, 'T4.1 compile --jobs')
i4 = jobs_of_top(error)
call assert(i4 == 1 .and. error == 0, 'T4.3 the top level --jobs keeps its default')
v = flag_of('compile', '--verbose', error)
call assert(v .and. error == 0, 'T4.1 compile --verbose')
call run('link -v')
v = flag_of('link', '--verbose', error)
call assert(v .and. error == 0, 'T4.4 link --verbose (subset)')
call define
call cli%parse(args='link -j 2', error=error)
call assert(error /= 0, 'T4.4 link has no --jobs')
out = read_back(lun)
! T4.2: the definitions are equal: the option block of the help, and the behaviour; usage after parse, which adds the
! builtins, so that it does not copy the CLI (the gfortran 16 trunk miscopies it: the accepted B33 regression)
call run('')
top = block_of(cli%usage(g=0), '   --jobs')
cmd = block_of(cli%usage(g=1), '   --jobs')
call assert(len(top) > 0, 'T4.2 the --jobs block')
call assert_equal(cmd, top, 'T4.2 --jobs: same help block')
call assert_equal(block_of(cli%usage(g=1), '   --verbose'), block_of(cli%usage(g=0), '   --verbose'), 'T4.2 --verbose')
call assert_equal(block_of(cli%usage(g=1), '   --scheme'), block_of(cli%usage(g=0), '   --scheme'), 'T4.2 --scheme')
call assert_equal(block_of(cli%usage(g=1), '   --restart'), block_of(cli%usage(g=0), '   --restart'), 'T4.2 --restart')
call assert_equal(block_of(cli%usage(g=1), '   --set'), block_of(cli%usage(g=0), '   --set'), 'T4.2 --set')
call assert_equal(block_of(cli%usage(g=1), '   -a'), block_of(cli%usage(g=0), '   -a'), 'T4.2 -a (exclude)')
call assert(index(cli%usage(g=1), '--secret') == 0, 'T4.2 hidden stays hidden')
call run('compile --jobs 999 --scheme WENO5 --no-restart --set a=1')
i4 = jobs_of_compile(error)
call assert(i4 == 64 .and. error == 0, 'T4.2 range and clamp copied')
s = scheme_of(error)
call assert(trim(s) == 'weno5' .and. error == 0, 'T4.2 case-insensitive choices copied')
v = flag_of('compile', '--restart', error)
call assert(.not.v .and. error == 0, 'T4.2 negation copied')
call define
call cli%parse(args='compile --set a', error=error)
call assert(error /= 0, 'T4.2 map copied')
call define
call cli%parse(args='compile --mesh-file missing.grd', error=error)
call assert(error /= 0, 'T4.2 path check copied')
call define(required=.true.)
call cli%parse(args='--need 1 compile', error=error)
call assert_equal(error, ERROR_MISSING_REQUIRED, 'T4.2 required copied')
out = read_back(lun)
! T4.8: the builtins are not duplicated
call define
call cli%parse(args='compile', error=error)
out = cli%usage(g=1)
call assert_equal(count_of(out, new_line('a')//'   --help'), 1_I4P, 'T4.8 one --help option in the command')
! T4.5-T4.7, T4.9: errors
call define(copy=.false.)
call cli%copy_options(to_group='compile', switches='--jobs,--bogus', error=error)
call assert_equal(error, ERROR_MISSING_CLA, 'T4.5 unknown switch')
call cli%parse(args='', error=error)
call assert(index(cli%usage(g=1), '--jobs') == 0, 'T4.5 nothing copied')
call define(copy=.false.)
call cli%add(group='compile', switch='--jobs', help='own', required=.false., act='store', def='2', error=error)
call cli%copy_options(to_group='compile', switches='--jobs', error=error)
call assert_equal(error, ERROR_GROUP_CONSISTENCY, 'T4.6 the target defines the switch')
call define(copy=.false.)
call cli%copy_options(to_group='compile', switches='FILE', error=error)
call assert_equal(error, ERROR_COPY_POSITIONAL, 'T4.7 a positional')
call define(copy=.false.)
call cli%copy_options(to_group='nothing', error=error)
call assert_equal(error, ERROR_MISSING_GROUP, 'T4.9 missing target')
call cli%copy_options(to_group='compile', from_group='nothing', error=error)
call assert_equal(error, ERROR_MISSING_GROUP, 'T4.9 missing source')
out = read_back(lun)
! T4.10: an exclude pair copied together is enforced in the target
call define
call cli%parse(args='compile -a -b', error=error)
call assert_equal(error, ERROR_M_EXCLUDE, 'T4.10 exclude pair in the target')
! T4.11: from a command to another; envvar: explicit verbatim, generated again for the target
call define(prefix='APP')
call cli%copy_options(to_group='test', from_group='compile', switches='--verbose,--jobs', error=error)
call assert_equal(error, 0_I4P, 'T4.11 copy from compile to test')
call cli%parse(args='test --verbose', error=error)
out = cli%usage(g=1)
call assert_contains(out, 'environment variable name "APP_COMPILE_JOBS"', 'auto envvar generated for compile')
call assert_contains(out, 'environment variable name "SOLVER_VERBOSE"', 'explicit envvar copied verbatim')
out = cli%usage(g=3)
call assert_contains(out, 'environment variable name "APP_TEST_JOBS"', 'auto envvar generated for test')
v = flag_of('test', '--verbose', error)
call assert(v .and. error == 0, 'T4.11 test --verbose')
! a range error is the copy's own
call define
call cli%parse(args='compile --cfl 2', error=error)
call assert_equal(cfl_error(), ERROR_OUT_OF_RANGE, 'range of the copy')
out = read_back(lun)
call capture_close(lun)

contains
  subroutine define(copy, required, prefix)
  !< Define the CLI: options at the top level, copied into compile (all) and link (--verbose).
  logical,      intent(in), optional :: copy     !< Copy the options (default .true.).
  logical,      intent(in), optional :: required !< Add a required option.
  character(*), intent(in), optional :: prefix   !< Prefix of the generated envvar names.
  logical                            :: copy_    !< Copy, local variable.

  copy_ = .true. ; if (present(copy)) copy_ = copy
  call cli%init(progname='flap_test_copy_options', error_lun=lun, usage_lun=lun, error_hint=.false., &
                auto_envvar_prefix=prefix)
  call cli%add(switch='--jobs', switch_ab='-j', help='parallel jobs', required=.false., act='store', def='1', min='1', &
               max='64', clamp=.true., error=error)
  call cli%add(switch='--verbose', switch_ab='-v', help='verbose', required=.false., act='store_true', def='.false.', &
               envvar='SOLVER_VERBOSE', error=error)
  call cli%add(switch='--scheme', help='scheme', required=.false., act='store', def='muscl', choices='weno5,muscl', &
               case_sensitive=.false., error=error)
  call cli%add(switch='--restart', switch_neg='--no-restart', help='restart', required=.false., act='store_true', &
               def='.true.', error=error)
  call cli%add(switch='--set', help='overrides', required=.false., act='store', nargs='*', map=.true., def='', error=error)
  call cli%add(switch='--mesh-file', help='mesh', required=.false., act='store', def='', must_exist=.true., error=error)
  call cli%add(switch='--secret', help='secret', required=.false., act='store', def='0', hidden=.true., error=error)
  call cli%add(switch='--cfl', help='cfl', required=.false., act='store', def='0.5', min='0', max='1', error=error)
  call cli%add(switch='-a', help='a', required=.false., act='store_true', def='.false.', exclude='-b', error=error)
  call cli%add(switch='-b', help='b', required=.false., act='store_true', def='.false.', error=error)
  call cli%add(positional=.true., position=1, switch='FILE', help='file', required=.false., act='store', def='x', &
               error=error)
  if (present(required)) then
    if (required) call cli%add(switch='--need', help='needed', required=.true., act='store', error=error)
  endif
  call assert_equal(error, 0_I4P, 'add the options')
  call cli%add_group(group='compile', description='compile', error=error)
  call cli%add_group(group='link', description='link', error=error)
  call cli%add_group(group='test', description='test', error=error)
  if (copy_) then
    call cli%copy_options(to_group='compile', error=error)
    call assert_equal(error, 0_I4P, 'copy_options to compile')
    call cli%copy_options(to_group='link', switches='--verbose', error=error)
    call assert_equal(error, 0_I4P, 'copy_options --verbose to link')
  endif
  endsubroutine define

  subroutine run(args)
  !< Define the CLI and parse a command line.
  character(*), intent(in) :: args !< Command line.

  call define
  call cli%parse(args=args, error=error)
  call assert_equal(error, 0_I4P, 'parse "'//args//'"')
  endsubroutine run

  function jobs_of_top(e) result(val)
  !< Value of --jobs of the top level.
  integer(I4P), intent(out) :: e   !< Error.
  integer(I4P)              :: val !< Value.

  val = -1
  call cli%get(switch='--jobs', val=val, error=e)
  endfunction jobs_of_top

  function jobs_of_compile(e) result(val)
  !< Value of --jobs of compile.
  integer(I4P), intent(out) :: e   !< Error.
  integer(I4P)              :: val !< Value.

  val = -1
  call cli%get(group='compile', switch='--jobs', val=val, error=e)
  endfunction jobs_of_compile

  function flag_of(group, switch, e) result(val)
  !< Value of a flag of a command.
  character(*), intent(in)  :: group  !< Group.
  character(*), intent(in)  :: switch !< Switch.
  integer(I4P), intent(out) :: e      !< Error.
  logical                   :: val    !< Value.

  val = .false.
  call cli%get(group=group, switch=switch, val=val, error=e)
  endfunction flag_of

  function scheme_of(e) result(val)
  !< Value of --scheme of compile.
  integer(I4P), intent(out) :: e   !< Error.
  character(99)             :: val !< Value.

  val = ''
  call cli%get(group='compile', switch='--scheme', val=val, error=e)
  endfunction scheme_of

  function cfl_error() result(e)
  !< Error of the get of --cfl of compile.
  integer(I4P) :: e   !< Error.
  real         :: val !< Value.

  val = 0.
  call cli%get(group='compile', switch='--cfl', val=val, error=e)
  endfunction cfl_error

  function block_of(text, head) result(block)
  !< The option block of a help text starting at a line beginning with head, up to the next option line ('' if none).
  character(*), intent(in)      :: text  !< Help text.
  character(*), intent(in)      :: head  !< Beginning of the option line.
  character(len=:), allocatable :: block !< Block.
  integer(I4P)                  :: b     !< Begin of the block.
  integer(I4P)                  :: e     !< End of the block.

  block = ''
  b = index(text, new_line('a')//head)
  if (b == 0) return
  b = b + 1
  e = index(text(b+1:), new_line('a')//'   -')
  if (e == 0) then
    block = text(b:)
  else
    block = text(b:b+e-1)
  endif
  endfunction block_of

  function count_of(text, what) result(n)
  !< Number of occurrences of a substring.
  character(*), intent(in) :: text !< Text.
  character(*), intent(in) :: what !< Substring.
  integer(I4P)             :: n    !< Occurrences.
  integer(I4P)             :: p    !< Position.
  integer(I4P)             :: i    !< Found position.

  n = 0
  p = 1
  do
    i = index(text(p:), what)
    if (i == 0) exit
    n = n + 1
    p = p + i + len(what) - 1
  enddo
  endfunction count_of
endprogram flap_test_copy_options
