add_group – FLAP
add_group Subroutine
37 statements
Source File
private subroutine add_group(self, help, description, exclude, examples, group)
Add CLAs group to CLI.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(inout) :: self
CLI data.
character(len=*), intent(in), optional :: help
Help message.
character(len=*), intent(in), optional :: description
Detailed description.
character(len=*), intent(in), optional :: exclude
Group name of the mutually exclusive group.
character(len=*), intent(in), optional :: examples(1:)
Examples of correct usage of the group.
character(len=*), intent(in) :: group
Name of the grouped CLAs.
Calls
Called by
Source Code
  subroutine add_group(self, help, description, exclude, examples, group)
  !< Add CLAs group to CLI.
  class(command_line_interface), intent(inout)    :: self              !< CLI data.
  character(*), optional,        intent(in)       :: help              !< Help message.
  character(*), optional,        intent(in)       :: description       !< Detailed description.
  character(*), optional,        intent(in)       :: exclude           !< Group name of the mutually exclusive group.
  character(*), optional,        intent(in)       :: examples(1:)      !< Examples of correct usage of the group.
  character(*),                  intent(in)       :: group             !< Name of the grouped CLAs.
  type(command_line_arguments_group), allocatable :: clasg_list_new(:) !< New (extended) CLAs group list.
  character(len=:), allocatable                   :: helpd             !< Help message.
  character(len=:), allocatable                   :: descriptiond      !< Detailed description.
  character(len=:), allocatable                   :: excluded          !< Group name of the mutually exclusive group.
  integer(I4P)                                    :: Ng                !< Number of groups.
  integer(I4P)                                    :: gi                !< Group index
  if (.not.self%is_defined_group(group=group)) then
    helpd        = 'usage: ' ; if (present(help       )) helpd        = help
    descriptiond = ''        ; if (present(description)) descriptiond = description
    excluded     = ''        ; if (present(exclude    )) excluded     = exclude
    Ng = size(self%clasg,dim=1)
    allocate(clasg_list_new(0:Ng))
!    clasg_list_new(0:Ng-1) = self%clasg(0:Ng-1) ! Not working on Intel Fortran 15.0.2
    do gi = 0, Ng-1
      clasg_list_new(gi) = self%clasg(gi)
    enddo
    call clasg_list_new(Ng)%assign_object(self)
    clasg_list_new(Ng)%help        = helpd
    clasg_list_new(Ng)%description = descriptiond
    clasg_list_new(Ng)%group       = group
    clasg_list_new(Ng)%m_exclude   = excluded
    call clasg_list_new(Ng)%set_examples(examples)
    deallocate(self%clasg)
    allocate(self%clasg(0:Ng))
    self%clasg = clasg_list_new
    deallocate(clasg_list_new)
  endif
  endsubroutine add_group
Call graph
add_group calls assign_object, is_defined_group, set_examples
add calls add_group
fake_call calls add_group, add, parse, get
flap_save_bash_completion calls add_group, add, parse
flap_test_group_examples calls add_group, add, get
flap_test_nested calls add_group, add, parse, get
parse calls add
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, parse, get_varying, get
flap_test_choices_logical calls add, parse, get
flap_test_duplicated_clas calls add, get
flap_test_group calls fake_call
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_string calls add, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse