assert_equal_i8 – FLAP
assert_equal_i8 Subroutine
9 statements
Source File
private subroutine assert_equal_i8(this, i1, i2)
Check if two integers (8 bits) are equal.
Type Bound
tester_t
Arguments
Type Intent Optional Attributes Name
class(tester_t), intent(inout) :: this
The tester.
integer(kind=int8), intent(in) :: i1
Value to compare.
integer(kind=int8), intent(in) :: i2
Value to compare.
Called by
Source Code
  subroutine assert_equal_i8(this, i1, i2)
    class(tester_t), intent(inout)        :: this !< The tester.
    integer(int8),   intent(in)           :: i1   !< Value to compare.
    integer(int8),   intent(in)           :: i2   !< Value to compare.
    this% n_tests = this% n_tests + 1
    if (i1 .ne. i2) then
       this% n_errors = this% n_errors + 1
    end if
  end subroutine assert_equal_i8
Call graph
flap_test_group calls assert_equal
test_tester_05 calls assert_equal
test_tester_1 calls assert_equal
test_tester_2 calls assert_equal
test_tester_3 calls assert_equal
test_tester_4 calls assert_equal
test_tester_7 calls assert_equal
test_tester_8 calls assert_equal