assign_object – FLAP
assign_object Subroutine
22 statements
Source File
private elemental subroutine assign_object(lhs, rhs)
Assign two abstract objects.
Type Bound
object
Arguments
Type Intent Optional Attributes Name
class(object), intent(inout) :: lhs
Left hand side.
class(object), intent(in) :: rhs
Rigth hand side.
Called by
Source Code
  elemental subroutine assign_object(lhs, rhs)
  !< Assign two abstract objects.
  class(object), intent(inout) :: lhs !< Left hand side.
  class(object), intent(in)    :: rhs !< Rigth hand side.
  if (allocated(rhs%progname     )) lhs%progname      = rhs%progname
  if (allocated(rhs%version      )) lhs%version       = rhs%version
  if (allocated(rhs%help         )) lhs%help          = rhs%help
  if (allocated(rhs%help_color   )) lhs%help_color    = rhs%help_color
  if (allocated(rhs%help_style   )) lhs%help_style    = rhs%help_style
  if (allocated(rhs%help_markdown)) lhs%help_markdown = rhs%help_markdown
  if (allocated(rhs%description  )) lhs%description   = rhs%description
  if (allocated(rhs%license      )) lhs%license       = rhs%license
  if (allocated(rhs%authors      )) lhs%authors       = rhs%authors
  if (allocated(rhs%epilog       )) lhs%epilog        = rhs%epilog
  if (allocated(rhs%m_exclude    )) lhs%m_exclude     = rhs%m_exclude
  if (allocated(rhs%error_message)) lhs%error_message = rhs%error_message
  if (allocated(rhs%error_color  )) lhs%error_color   = rhs%error_color
  if (allocated(rhs%error_style  )) lhs%error_style   = rhs%error_style
                                    lhs%error         = rhs%error
                                    lhs%usage_lun     = rhs%usage_lun
                                    lhs%version_lun   = rhs%version_lun
                                    lhs%error_lun     = rhs%error_lun
  endsubroutine assign_object
Call graph
add_group calls assign_object
add calls assign_object, add_group
cla_assign_cla calls assign_object
clasg_assign_clasg calls assign_object
cli_assign_cli calls assign_object
init calls assign_object
parse calls assign_object, add, parse
fake_call calls add_group, add, init, parse, get
flap_save_bash_completion calls add_group, add, init, parse
flap_save_man_page calls add, init, get
flap_save_usage_to_markdown calls add, init, get
flap_test_action_store calls add, init, get_varying, get
flap_test_ansi_color_style calls add, init, get
flap_test_basic calls add, init, parse, get_varying, get
flap_test_choices_logical calls add, init, parse, get
flap_test_duplicated_clas calls add, init, get
flap_test_group_examples calls add_group, add, init, get
flap_test_hidden calls add, init, get
flap_test_ignore_unknown_clas calls add, init, get
flap_test_minimal calls add, init, get
flap_test_nargs_insufficient calls add, init, get
flap_test_nested calls add_group, add, init, parse, get
flap_test_string calls add, init, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_test_group calls fake_call