check – FLAP
check Subroutine
27 statements
Source File
private subroutine check(self, pref)
Check data consistency.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(inout) :: self
CLAsG data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Called by
Source Code
  subroutine check(self, pref)
  !< Check data consistency.
  class(command_line_arguments_group), intent(inout) :: self  !< CLAsG data.
  character(*), optional,              intent(in)    :: pref  !< Prefixing string.
  integer(I4P)                                       :: a     !< Counter.
  integer(I4P)                                       :: aa    !< Counter.
  ! verify if CLAs switches are unique
  CLA_unique: do a=1, self%Na
    if (.not.self%cla(a)%is_positional) then
      do aa=1, self%Na
        if ((a/=aa).and.(.not.self%cla(aa)%is_positional)) then
          if ((self%cla(a)%switch==self%cla(aa)%switch   ).or.(self%cla(a)%switch_ab==self%cla(aa)%switch   ).or.&
              (self%cla(a)%switch==self%cla(aa)%switch_ab).or.(self%cla(a)%switch_ab==self%cla(aa)%switch_ab)) then
            call self%errored(pref=pref, error=ERROR_CONSISTENCY, a1=a, a2=aa)
            exit CLA_unique
          endif
        endif
      enddo
    endif
  enddo CLA_unique
  ! update mutually exclusive relations
  CLA_exclude: do a=1, self%Na
    if (.not.self%cla(a)%is_positional) then
      if (self%cla(a)%m_exclude/='') then
        if (self%is_defined(switch=self%cla(a)%m_exclude, pos=aa)) then
          self%cla(aa)%m_exclude = self%cla(a)%switch
        endif
      endif
    endif
  enddo CLA_exclude
  endsubroutine check
Call graph
check calls errored, is_defined, check
errored calls colorize, print_error_message, str
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
add calls check, add
parse calls add, check, parse
fake_call calls add, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls add, parse
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, parse, get_varying, get
flap_test_choices_logical calls add, parse, get
flap_test_duplicated_clas calls add, get
flap_test_group_examples calls add, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_nested calls add, parse, get
flap_test_string calls add, parse, get
flap_test_group calls fake_call