check_m_exclude_consistency – FLAP
check_m_exclude_consistency Subroutine
12 statements
Source File
private subroutine check_m_exclude_consistency(self, pref)
Check mutually exclusion consistency.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Called by
Source Code
  subroutine check_m_exclude_consistency(self, pref)
  !< Check mutually exclusion consistency.
  class(command_line_argument), intent(inout) :: self  !< CLA data.
  character(*), optional,       intent(in)    :: pref  !< Prefixing string.
  if ((self%is_required).and.(self%m_exclude/='')) then
    call self%errored(pref=pref, error=ERROR_REQUIRED_M_EXCLUDE)
    return
  endif
  if ((self%is_positional).and.(self%m_exclude/='')) then
    call self%errored(pref=pref, error=ERROR_POSITIONAL_M_EXCLUDE)
    return
  endif
  endsubroutine check_m_exclude_consistency
Call graph
check_m_exclude_consistency calls errored
errored calls colorize, print_error_message, str
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
check calls check_m_exclude_consistency
add calls check
fake_call calls add, parse, get
parse calls add
flap_save_bash_completion calls add, parse
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, parse, get_varying, get
flap_test_choices_logical calls add, parse, get
flap_test_duplicated_clas calls add, get
flap_test_group_examples calls add, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_nested calls add, parse, get
flap_test_string calls add, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_test_group calls fake_call