check_list_size – FLAP
check_list_size Function
16 statements
Source File
private function check_list_size(self, Nv, val, pref) result(is_ok)
Check CLA multiple values list size consistency.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
integer(kind=I4P), intent(in) :: Nv
Number of values.
character(len=*), intent(in) :: val
First value.
character(len=*), intent(in), optional :: pref
Prefixing string.
Return Value logical
Check result.
Calls
Called by
Source Code
  function check_list_size(self, Nv, val, pref) result(is_ok)
  !< Check CLA multiple values list size consistency.
  class(command_line_argument), intent(inout) :: self  !< CLA data.
  integer(I4P),                 intent(in)    :: Nv    !< Number of values.
  character(*),                 intent(in)    :: val   !< First value.
  character(*), optional,       intent(in)    :: pref  !< Prefixing string.
  logical                                     :: is_ok !< Check result.
  is_ok = .true.
  if (Nv==1) then
    if (trim(adjustl(val))=='') then
      ! there is no real value, but only for nargs=+ this is a real error
      is_ok = .false.
      if (self%nargs=='+') then
        call self%errored(pref=pref, error=ERROR_NARGS_INSUFFICIENT)
      endif
    endif
  endif
  endfunction check_list_size
Call graph
check_list_size calls errored
errored calls colorize, print_error_message, str
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
get_cla_list_varying_char calls check_list_size, get_varying
get_cla_list_varying_i1p calls check_list_size, get_varying
get_cla_list_varying_i2p calls check_list_size, get_varying
get_cla_list_varying_i4p calls check_list_size, get_varying
get_cla_list_varying_i8p calls check_list_size, get_varying
get_cla_list_varying_logical calls check_list_size, get_varying
get_cla_list_varying_r16p calls check_list_size, get_varying
get_cla_list_varying_r4p calls check_list_size, get_varying
get_cla_list_varying_r8p calls check_list_size, get_varying
flap_test_action_store calls get_varying
flap_test_basic calls get_varying