check_choices – FLAP
check_choices Subroutine
57 statements
Source File
private subroutine check_choices(self, val, pref)
Check if CLA value is in allowed choices.
Note
This procedure can be called if and only if cla%choices has been allocated.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
class(*), intent(in) :: val
CLA value.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Called by
Source Code
  subroutine check_choices(self, val, pref)
  !< Check if CLA value is in allowed choices.
  !<
  !< @note This procedure can be called if and only if cla%choices has been allocated.
  class(command_line_argument), intent(inout) :: self    !< CLA data.
  class(*),                     intent(in)    :: val     !< CLA value.
  character(*), optional,       intent(in)    :: pref    !< Prefixing string.
  character(len(self%choices)), allocatable   :: toks(:) !< Tokens for parsing choices list.
  integer(I4P)                                :: Nc      !< Number of choices.
  logical                                     :: val_in  !< Flag for checking if val is in the choosen range.
  character(len=:), allocatable               :: val_str !< Value in string form.
  character(len=:), allocatable               :: tmp     !< Temporary string for avoiding GNU gfrotran bug.
  integer(I4P)                                :: c       !< Counter.
  val_in = .false.
  val_str = ''
  tmp = self%choices
  call tokenize(strin=tmp, delimiter=',', toks=toks, Nt=Nc)
  select type(val)
#if defined _R16P
  type is(real(R16P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1._R16P)) val_in = .true.
    enddo
#endif
  type is(real(R8P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1._R8P)) val_in = .true.
    enddo
  type is(real(R4P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1._R4P)) val_in = .true.
    enddo
  type is(integer(I8P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1_I8P)) val_in = .true.
    enddo
  type is(integer(I4P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1_I4P)) val_in = .true.
    enddo
  type is(integer(I2P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1_I2P)) val_in = .true.
    enddo
  type is(integer(I1P))
    val_str = str(n=val)
    do c=1, Nc
      if (val==cton(str=trim(adjustl(toks(c))), knd=1_I1P)) val_in = .true.
    enddo
  type is(character(*))
    val_str = val
    do c=1, Nc
      if (val==toks(c)) val_in = .true.
    enddo
  type is(logical)
    call self%errored(pref=pref, error=ERROR_CHOICES_LOGICAL)
  endselect
  if (.not.val_in.and.(self%error==0)) then
    call self%errored(pref=pref, error=ERROR_NOT_IN_CHOICES, val_str=val_str)
  endif
  endsubroutine check_choices
Call graph
check_choices calls cton, errored, tokenize, str
errored calls print_error_message
get_cla calls check_choices, get
get_cla_list_from_buffer calls check_choices
get_cla_list calls get_cla_list_from_buffer, get
fake_call calls get
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_action_store calls get
flap_test_ansi_color_style calls get
flap_test_basic calls get
flap_test_choices_logical calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get
flap_test_nested calls get
flap_test_string calls get
flap_test_group calls fake_call