colorize_default – FLAP
colorize_default Function
21 statements
Source File
private pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
Colorize and stylize strings, DEFAULT kind.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Input string.
character(len=*), intent(in), optional :: color_fg
Foreground color definition.
character(len=*), intent(in), optional :: color_bg
Background color definition.
character(len=*), intent(in), optional :: style
Style definition.
Return Value character(len=:), allocatable
Colorized string.
Calls
Called by
Source Code
   pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
   !< Colorize and stylize strings, DEFAULT kind.
   character(len=*), intent(in)           :: string    !< Input string.
   character(len=*), intent(in), optional :: color_fg  !< Foreground color definition.
   character(len=*), intent(in), optional :: color_bg  !< Background color definition.
   character(len=*), intent(in), optional :: style     !< Style definition.
   character(len=:), allocatable          :: colorized !< Colorized string.
   integer(int32)                         :: i         !< Counter.
   colorized = string
   if (present(color_fg)) then
      i = color_index(upper(color_fg))
      if (i>0) colorized = CODE_START//trim(COLORS_FG(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   if (present(color_bg)) then
      i = color_index(upper(color_bg))
      if (i>0) colorized = CODE_START//trim(COLORS_BG(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   if (present(style)) then
      i = style_index(upper(style))
      if (i>0) colorized = CODE_START//trim(STYLES(2, i))//CODE_END//colorized//CODE_CLEAR
   endif
   endfunction colorize_default
Call graph
colorize_default calls color_index, style_index, upper
colorize calls colorize_default
colors_samples calls colorize
errored calls colorize
styles_samples calls colorize
usage calls colorize, usage
face_test_colors calls colorize
face_test_styles calls colorize
check calls errored, check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, check
check_action_consistency calls errored
check_choices calls errored
check_envvar_consistency calls errored
check_list_size calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
get_cla calls errored, check_choices, get_cla_from_buffer, is_required_passed, get, parse
get_cla_from_buffer calls errored
get_cla_list calls errored, get_cla_list_from_buffer, is_required_passed, get, parse
get_cla_list_from_buffer calls errored, check_choices
get_cla_list_varying_char calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i1p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i2p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i8p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_logical calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r16p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r8p calls errored, check_list_size, is_required_passed, get_varying, parse
is_required_passed calls errored, is_required_passed, usage
is_required_val_passed calls errored
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
face_test_basic calls colors_samples, styles_samples
add calls check, add
check_m_exclusive calls raise_error_m_exclude
parse calls raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing, add, check_m_exclusive, check, is_required_passed, parse, usage, save_usage_to_markdown
fake_call calls get, add, parse
print_usage calls usage
save_man_page calls usage
save_usage_to_markdown calls usage
flap_save_man_page calls get, add, save_man_page
flap_save_usage_to_markdown calls get, add, save_usage_to_markdown
flap_test_action_store calls get_varying, get, add
flap_test_ansi_color_style calls get, add
flap_test_basic calls get_varying, get, add, parse, save_man_page
flap_test_choices_logical calls get, add, parse
flap_test_duplicated_clas calls get, add
flap_test_group_examples calls get, add
flap_test_hidden calls get, add
flap_test_ignore_unknown_clas calls get, add
flap_test_minimal calls get, add
flap_test_nargs_insufficient calls get, add
flap_test_nested calls get, add, parse
flap_test_string calls get, add, parse
flap_save_bash_completion calls add, parse
flap_test_group calls fake_call