color_index – FLAP
color_index Function
12 statements
Source File
private elemental function color_index(color)
Return the array-index corresponding to the queried color.
Note
Because Foreground and backround colors lists share the same name, no matter what array is used to find the color index. Thus, the foreground array is used.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: color
Color definition.
Return Value integer(kind=int32)
Index into the colors arrays.
Called by
Source Code
   elemental function color_index(color)
   !< Return the array-index corresponding to the queried color.
   !<
   !< @note Because Foreground and backround colors lists share the same name, no matter what array is used to find the color index.
   !< Thus, the foreground array is used.
   character(len=*), intent(in) :: color       !< Color definition.
   integer(int32)               :: color_index !< Index into the colors arrays.
   integer(int32)               :: c           !< Counter.
   color_index = 0
   do c=1, size(COLORS_FG, dim=2)
      if (trim(COLORS_FG(1, c))==trim(adjustl(color))) then
         color_index = c
         exit
      endif
   enddo
   endfunction color_index
Call graph
colorize_ascii calls color_index
colorize_default calls color_index
colorize_ucs4 calls color_index
colorize calls colorize_default
colors_samples calls colorize
errored calls colorize
styles_samples calls colorize
usage calls colorize, usage
face_test_colors calls colorize
face_test_styles calls colorize
check calls errored, check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, check
check_action_consistency calls errored
check_choices calls errored
check_envvar_consistency calls errored
check_list_size calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
get_cla calls errored, check_choices, get_cla_from_buffer, is_required_passed, get, parse
get_cla_from_buffer calls errored
get_cla_list calls errored, get_cla_list_from_buffer, is_required_passed, get, parse
get_cla_list_from_buffer calls errored, check_choices
get_cla_list_varying_char calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i1p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i2p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i8p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_logical calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r16p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r8p calls errored, check_list_size, is_required_passed, get_varying, parse
is_required_passed calls errored, is_required_passed, usage
is_required_val_passed calls errored
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
face_test_basic calls colors_samples, styles_samples
add calls check, add
check_m_exclusive calls raise_error_m_exclude
parse calls raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing, add, check_m_exclusive, check, is_required_passed, parse, usage, save_usage_to_markdown
fake_call calls get, add, parse
print_usage calls usage
save_man_page calls usage
save_usage_to_markdown calls usage
flap_save_man_page calls get, add, save_man_page
flap_save_usage_to_markdown calls get, add, save_usage_to_markdown
flap_test_action_store calls get_varying, get, add
flap_test_ansi_color_style calls get, add
flap_test_basic calls get_varying, get, add, parse, save_man_page
flap_test_choices_logical calls get, add, parse
flap_test_duplicated_clas calls get, add
flap_test_group_examples calls get, add
flap_test_hidden calls get, add
flap_test_ignore_unknown_clas calls get, add
flap_test_minimal calls get, add
flap_test_nargs_insufficient calls get, add
flap_test_nested calls get, add, parse
flap_test_string calls get, add, parse
flap_save_bash_completion calls add, parse
flap_test_group calls fake_call