errored – FLAP
errored Subroutine
25 statements
Source File
private subroutine errored(self, error, pref, group, switch)
Trig error occurrence and print meaningful message.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(inout) :: self
Object data.
integer(kind=I4P), intent(in) :: error
Error occurred.
character(len=*), intent(in), optional :: pref
Prefixing string.
character(len=*), intent(in), optional :: group
Group name.
character(len=*), intent(in), optional :: switch
CLA switch name.
Calls
Called by
Source Code
  subroutine errored(self, error, pref, group, switch)
  !< Trig error occurrence and print meaningful message.
  class(command_line_interface), intent(inout) :: self   !< Object data.
  integer(I4P),                  intent(in)    :: error  !< Error occurred.
  character(*), optional,        intent(in)    :: pref   !< Prefixing string.
  character(*), optional,        intent(in)    :: group  !< Group name.
  character(*), optional,        intent(in)    :: switch !< CLA switch name.
  character(len=:), allocatable                :: prefd  !< Prefixing string.
  self%error = error
  if (self%error/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    prefd = prefd//self%progname//': '//colorize('error', color_fg=self%error_color, style=self%error_style)
    select case(self%error)
    case(ERROR_MISSING_CLA)
      self%error_message = prefd//': there is no option "'//trim(adjustl(switch))//'"!'
    case(ERROR_MISSING_SELECTION_CLA)
      self%error_message = prefd//': to get an option value one of switch "name" or "position" must be provided!'
    case(ERROR_MISSING_GROUP)
      self%error_message = prefd//': ther is no group (command) named "'//trim(adjustl(group))//'"!'
    case(ERROR_TOO_FEW_CLAS)
      ! self%error_message = prefd//': too few arguments ('//trim(str(.true.,Na))//')'//&
                         ! ' respect the required ('//trim(str(.true.,self%Na_required))//')'
    endselect
    write(self%error_lun,'(A)')
    call self%print_error_message
  endif
  endsubroutine errored
Call graph
errored calls colorize, print_error_message
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
get_cla_list_varying_char calls errored
get_cla_list_varying_i1p calls errored
get_cla_list_varying_i2p calls errored
get_cla_list_varying_i4p calls errored
get_cla_list_varying_i8p calls errored
get_cla_list_varying_logical calls errored
get_cla_list_varying_r16p calls errored
get_cla_list_varying_r4p calls errored
get_cla_list_varying_r8p calls errored
get_cla_list calls errored
get_cla calls errored
fake_call calls get
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_basic calls get_varying, get
flap_test_choices_logical calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get
flap_test_nested calls get
flap_test_string calls get
flap_test_group calls fake_call