errored – FLAP
errored Subroutine
28 statements
Source File
private subroutine errored(self, error, pref, a1, a2)
Trig error occurrence and print meaningful message.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(inout) :: self
CLAsG data.
integer(kind=I4P), intent(in) :: error
Error occurred.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(in), optional :: a1
First index CLAs group inconsistent.
integer(kind=I4P), intent(in), optional :: a2
Second index CLAs group inconsistent.
Calls
Called by
Source Code
  subroutine errored(self, error, pref, a1, a2)
  !< Trig error occurrence and print meaningful message.
  class(command_line_arguments_group), intent(inout) :: self  !< CLAsG data.
  integer(I4P),                        intent(in)    :: error !< Error occurred.
  character(*), optional,              intent(in)    :: pref  !< Prefixing string.
  integer(I4P), optional,              intent(in)    :: a1    !< First index CLAs group inconsistent.
  integer(I4P), optional,              intent(in)    :: a2    !< Second index CLAs group inconsistent.
  character(len=:), allocatable                      :: prefd !< Prefixing string.
  self%error = error
  if (self%error/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    prefd = prefd//self%progname//': '//colorize('error', color_fg=self%error_color, style=self%error_style)
    select case(self%error)
    case(ERROR_CONSISTENCY)
      if (self%group /= '') then
        self%error_message = prefd//': group (command) name: "'//self%group//'" consistency error:'
      else
        self%error_message = prefd//': consistency error:'
      endif
      self%error_message = self%error_message//' "'//trim(str(a1, .true.))//             &
                           '-th" option has the same switch or abbreviated switch of "'//&
                           trim(str(a2, .true.))//'-th" option:'//new_line('a')
      self%error_message = self%error_message//prefd//' CLA('//trim(str(a1, .true.)) //') switches = '//self%cla(a1)%switch //' '//&
                           self%cla(a1)%switch_ab//new_line('a')
      self%error_message = self%error_message//prefd//' CLA('//trim(str(a2, .true.))//') switches = '//self%cla(a2)%switch//' '//&
                           self%cla(a2)%switch_ab
    case(ERROR_M_EXCLUDE)
      self%error_message = prefd//': the group "'//self%group//'" and "'//self%m_exclude//'" are mutually'//&
                           ' exclusive, but both have been called!'
    endselect
    call self%print_error_message
  endif
  endsubroutine errored
Call graph
errored calls colorize, print_error_message, str
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
check calls errored, check
raise_error_m_exclude calls errored
add calls check, add
check_m_exclusive calls raise_error_m_exclude
parse calls add, check_m_exclusive, check, parse
fake_call calls add, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls add, parse
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, parse, get_varying, get
flap_test_choices_logical calls add, parse, get
flap_test_duplicated_clas calls add, get
flap_test_group_examples calls add, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_nested calls add, parse, get
flap_test_string calls add, parse, get
flap_test_group calls fake_call