fake_call – FLAP
fake_call Subroutine
24 statements
Source File
subroutine fake_call(args, spectrum, domain, grid)
Wrapper for fake calls.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: args
Fake arguments.
logical, intent(out) :: spectrum
Spectrum value.
logical, intent(out) :: domain
Domain value.
logical, intent(out) :: grid
Grid value.
Calls
Called by
Source Code
  subroutine fake_call(args, spectrum, domain, grid)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Wrapper for fake calls.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in)     :: args     !< Fake arguments.
  logical,      intent(out)    :: spectrum !< Spectrum value.
  logical,      intent(out)    :: domain   !< Domain value.
  logical,      intent(out)    :: grid     !< Grid value.
  type(command_line_interface) :: cli      !< Command Line Interface (CLI).
  integer(I4P)                 :: error    !< Error trapping flag.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  call cli%init
  call cli%add_group(group='new', description='create new instance')
  call cli%add(group='new', switch='--spectrum', switch_ab='-s',            &
               help='Create new spectrum', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%add(group='new', switch='--domain', switch_ab='-d',            &
               help='Create new domain', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%add(group='new', switch='--grid', switch_ab='-g',            &
               help='Create new grid', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%parse(args=args, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--spectrum', val=spectrum, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--domain', val=domain, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--grid', val=grid, error=error)
  if (error/=0) stop
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine fake_call
Call graph
fake_call calls get, add_group, add, init, parse
add_group calls assign_object, is_defined_group, set_examples
add calls add_group, add, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, is_defined_group, check, is_defined, errored
get_cla_list calls parse, is_defined_group, get, errored, is_required_passed, tokenize, get_cla_list_from_buffer
get_cla calls parse, is_defined_group, get, errored, is_required_passed, check_choices, get_cla_from_buffer
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, cton, colorize, replace_all, str
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, cton, str, has_choices
colorize calls colorize_default
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
check_choices calls cton, errored, tokenize, str
colorize_default calls color_index, style_index, upper
get_cla_from_buffer calls cton, errored
get_cla_list_from_buffer calls cton, errored, tokenize, check_choices
flap_test_group calls fake_call