get_cla_list_varying_logical – FLAP
get_cla_list_varying_logical Subroutine
48 statements
Source File
private subroutine get_cla_list_varying_logical(self, val, pref, args, group, switch, position, error)
Get CLA multiple values from CLAs list parsed with varying size list, logical.
Note
The CLA list is returned deallocated if values are not correctly gotten.
Note
For logical type CLA the value is directly read without any robust error trapping.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(inout) :: self
CLI data.
logical, intent(out), allocatable :: val(:)
CLA values.
character(len=*), intent(in), optional :: pref
Prefixing string.
character(len=*), intent(in), optional :: args
String containing command line arguments.
character(len=*), intent(in), optional :: group
Name of group (command) of CLA.
character(len=*), intent(in), optional :: switch
Switch name.
integer(kind=I4P), intent(in), optional :: position
Position of positional CLA.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag.
Calls
Called by
Source Code
  subroutine get_cla_list_varying_logical(self, val, pref, args, group, switch, position, error)
  !< Get CLA multiple values from CLAs list parsed with varying size list, logical.
  !<
  !< @note The CLA list is returned deallocated if values are not correctly gotten.
  !<
  !< @note For logical type CLA the value is directly read without any robust error trapping.
  class(command_line_interface), intent(inout) :: self     !< CLI data.
  logical, allocatable,          intent(out)   :: val(:)   !< CLA values.
  character(*), optional,        intent(in)    :: pref     !< Prefixing string.
  character(*), optional,        intent(in)    :: args     !< String containing command line arguments.
  character(*), optional,        intent(in)    :: group    !< Name of group (command) of CLA.
  character(*), optional,        intent(in)    :: switch   !< Switch name.
  integer(I4P), optional,        intent(in)    :: position !< Position of positional CLA.
  integer(I4P), optional,        intent(out)   :: error    !< Error trapping flag.
  logical                                      :: found    !< Flag for checking if CLA containing switch has been found.
  integer(I4P)                                 :: g        !< Group counter.
  integer(I4P)                                 :: a        !< Argument counter.
  if (.not.self%is_parsed_) then
    call self%parse(pref=pref, args=args, error=error)
    if (self%error>0.and.self%error_unknown_clas/=ERROR_UNKNOWN_CLAS_IGNORED) return
  endif
  if (present(group)) then
    if (.not.self%is_defined_group(group=group, g=g)) then
      call self%errored(pref=pref, error=ERROR_MISSING_GROUP, group=group)
    endif
  else
    g = 0
  endif
  if (present(switch)) then
    ! search for the CLA corresponding to switch
    found = .false.
    do a=1, self%clasg(g)%Na
      if (.not.self%clasg(g)%cla(a)%is_positional) then
        if ((self%clasg(g)%cla(a)%switch==switch).or.(self%clasg(g)%cla(a)%switch_ab==switch)) then
          found = .true.
          exit
        endif
      endif
    enddo
    if (.not.found) then
      call self%errored(pref=pref, error=ERROR_MISSING_CLA, switch=switch)
    else
      call self%clasg(g)%cla(a)%get_varying(pref=pref, val=val) ; self%error = self%clasg(g)%cla(a)%error
    endif
  elseif (present(position)) then
    call self%clasg(g)%cla(position)%get_varying(pref=pref, val=val) ; self%error = error
  else
    call self%errored(pref=pref, error=ERROR_MISSING_SELECTION_CLA)
  endif
  ! check if the only error found is for unknown passed CLAs and if it is ignored by the user
  if (self%error==ERROR_UNKNOWN.and.self%error_unknown_clas==ERROR_UNKNOWN_CLAS_IGNORED) self%error = ERROR_UNKNOWN_CLAS_IGNORED
  if (present(error)) error = self%error
  endsubroutine get_cla_list_varying_logical
Call graph
get_cla_list_varying_logical calls get_varying, errored, is_defined_group, parse, check_list_size, is_required_passed, tokenize
errored calls colorize, print_error_message, str
parse calls get_args, add, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, cton, assign_object, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
colorize calls colorize_default
add calls is_defined_group, add, add_group, assign_object, check, upper_case
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls is_defined_group, check, is_defined, errored, check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency
get_cla_list_varying_char calls check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_i1p calls cton, check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_i2p calls cton, check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_i4p calls cton, check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_i8p calls cton, check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_r4p calls cton, check_list_size, errored, is_required_passed, tokenize
get_cla_list_varying_r8p calls cton, check_list_size, errored, is_required_passed, tokenize
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, colorize, cton, replace_all, str
add_group calls is_defined_group, assign_object, set_examples
check_list_size calls errored
colorize_default calls color_index, style_index, upper
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls tokenize, get_clasg_indexes
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, cton, str, has_choices
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
flap_test_action_store calls get_varying
flap_test_basic calls get_varying