get_cla_list_varying_char – FLAP
get_cla_list_varying_char Subroutine
31 statements
Source File
private subroutine get_cla_list_varying_char(self, val, pref)
Get CLA (multiple) value with varying size, character.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
character(len=*), intent(out), allocatable :: val(:)
CLA values.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Called by
Source Code
  subroutine get_cla_list_varying_char(self, val, pref)
  !< Get CLA (multiple) value with varying size, character.
  class(command_line_argument), intent(inout) :: self     !< CLA data.
  character(*), allocatable,    intent(out)   :: val(:)   !< CLA values.
  character(*), optional,       intent(in)    :: pref     !< Prefixing string.
  integer(I4P)                                :: Nv       !< Number of values.
  character(len=len(self%val)), allocatable   :: valsV(:) !< String array of values based on self%val.
  character(len=len(self%def)), allocatable   :: valsD(:) !< String array of values based on self%def.
  integer(I4P)                                :: v        !< Values counter.
  if (.not.self%is_required_passed(pref=pref)) return
  if (.not.allocated(self%nargs)) then
     call self%errored(pref=pref, error=ERROR_NO_LIST)
     return
  endif
  if (self%act==action_store) then
     if (self%is_passed) then
        call tokenize(strin=self%val, delimiter=ARGS_SEP, toks=valsV, Nt=Nv)
        if (.not.self%check_list_size(Nv=Nv, val=valsV(1), pref=pref)) return
        allocate(val(1:Nv))
        do v=1, Nv
           val(v) = trim(adjustl(valsV(v)))
        enddo
     else ! using default value
        call tokenize(strin=self%def, delimiter=ARGS_SEP, toks=valsD, Nt=Nv)
        if (.not.self%check_list_size(Nv=Nv, val=valsD(1), pref=pref)) return
        allocate(val(1:Nv))
        do v=1, Nv
          val(v) = trim(adjustl(valsD(v)))
        enddo
     endif
  endif
  endsubroutine get_cla_list_varying_char
Call graph
get_cla_list_varying_char calls check_list_size, errored, is_required_passed, tokenize, get_varying
check_list_size calls errored
errored calls colorize, print_error_message, str
is_required_passed calls errored
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
get_cla_list_varying_i1p calls get_varying
get_cla_list_varying_i2p calls get_varying
get_cla_list_varying_i4p calls get_varying
get_cla_list_varying_i8p calls get_varying
get_cla_list_varying_logical calls get_varying
get_cla_list_varying_r16p calls get_varying
get_cla_list_varying_r4p calls get_varying
get_cla_list_varying_r8p calls get_varying
flap_test_action_store calls get_varying
flap_test_basic calls get_varying