get_cla_list – FLAP
get_cla_list Subroutine
50 statements
Source File
private subroutine get_cla_list(self, pref, val)
Get CLA multiple values.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
character(len=*), intent(in), optional :: pref
Prefixing string.
class(*), intent(inout) :: val(1:)
CLA values.
Calls
Called by
Source Code
  subroutine get_cla_list(self, pref, val)
  !< Get CLA multiple values.
  class(command_line_argument), intent(inout) :: self     !< CLA data.
  character(*), optional,       intent(in)    :: pref     !< Prefixing string.
  class(*),                     intent(inout) :: val(1:)  !< CLA values.
  integer(I4P)                                :: Nv       !< Number of values.
  character(len=len(self%def)), allocatable   :: valsD(:) !< String array of values based on self%def.
  integer(I4P)                                :: v        !< Values counter.
  if (.not.self%is_required_passed(pref=pref)) return
  if (.not.allocated(self%nargs)) then
    call self%errored(pref=pref,error=ERROR_NO_LIST)
    return
  endif
  if (self%act==action_store) then
    if (self%is_passed) then
      call self%get_cla_list_from_buffer(buffer=self%val, val=val, pref=pref)
    else ! using default value
      call self%get_cla_list_from_buffer(buffer=self%def, val=val, pref=pref)
    endif
  elseif (self%act==action_store_true) then
    if (self%is_passed) then
      select type(val)
      type is(logical)
        val = .true.
      endselect
    else
      call tokenize(strin=self%def, delimiter=' ', toks=valsD, Nt=Nv)
      select type(val)
      type is(logical)
        do v=1,Nv
          read(valsD(v),*)val(v)
        enddo
      endselect
    endif
  elseif (self%act==action_store_false) then
    if (self%is_passed) then
      select type(val)
      type is(logical)
        val = .false.
      endselect
    else
      call tokenize(strin=self%def, delimiter=' ', toks=valsD, Nt=Nv)
      select type(val)
      type is(logical)
        do v=1, Nv
          read(valsD(v),*)val(v)
        enddo
      endselect
    endif
  endif
  endsubroutine get_cla_list
Call graph
get_cla_list calls errored, get_cla_list_from_buffer, is_required_passed, tokenize, get
errored calls colorize, print_error_message, str
get_cla_list_from_buffer calls errored, tokenize, cton, check_choices
is_required_passed calls errored
colorize calls colorize_default
check_choices calls errored, tokenize, cton, str
colorize_default calls color_index, style_index, upper
get_cla calls get
fake_call calls get
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_action_store calls get
flap_test_ansi_color_style calls get
flap_test_basic calls get
flap_test_choices_logical calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get
flap_test_nested calls get
flap_test_string calls get
flap_test_group calls fake_call