has_choices – FLAP
has_choices Function
5 statements
Source File
private pure function has_choices(self)
Return true if CLA has choices.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(in) :: self
CLA data.
Return Value logical
Check result.
Called by
Source Code
  pure function has_choices(self)
  !< Return true if CLA has choices.
  class(command_line_argument), intent(in) :: self        !< CLA data.
  logical                                  :: has_choices !< Check result.
  has_choices = allocated(self%choices)
  endfunction has_choices
Call graph
signature calls has_choices, signature
save_bash_completion calls signature
usage calls signature, usage
is_required_passed calls usage
save_man_page calls signature, usage
save_usage_to_markdown calls signature, usage
flap_save_bash_completion calls save_bash_completion, parse
parse calls is_required_passed, save_usage_to_markdown, usage
print_usage calls usage
flap_save_man_page calls save_man_page, get
flap_save_usage_to_markdown calls save_usage_to_markdown, get
flap_test_basic calls save_man_page, parse, get_varying, get
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get