is_defined_group – FLAP
is_defined_group Function
15 statements
Source File
private function is_defined_group(self, group, g) result(defined)
Check if a CLAs group has been defined.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(in) :: self
CLI data.
character(len=*), intent(in) :: group
Name of group (command) of CLAs.
integer(kind=I4P), intent(out), optional :: g
Index of group.
Return Value logical
Check if a CLAs group has been defined.
Called by
Source Code
  function is_defined_group(self, group, g) result(defined)
  !< Check if a CLAs group has been defined.
  class(command_line_interface), intent(in)  :: self    !< CLI data.
  character(*),                  intent(in)  :: group   !< Name of group (command) of CLAs.
  integer(I4P), optional,        intent(out) :: g       !< Index of group.
  logical                                    :: defined !< Check if a CLAs group has been defined.
  integer(I4P)                               :: gg      !< Counter.
  integer(I4P)                               :: ggg     !< Counter.
  defined = .false.
  do gg=0, size(self%clasg,dim=1)-1
    ggg = gg
    if (allocated(self%clasg(gg)%group)) defined = (self%clasg(gg)%group==group)
    if (defined) exit
  enddo
  if (present(g)) g = ggg
  endfunction is_defined_group
Call graph
add_group calls is_defined_group
add calls is_defined_group, add_group
check_m_exclusive calls is_defined_group
check calls is_defined_group
get_cla_list_varying_char calls is_defined_group, parse
get_cla_list_varying_i1p calls is_defined_group, parse
get_cla_list_varying_i2p calls is_defined_group, parse
get_cla_list_varying_i4p calls is_defined_group, parse
get_cla_list_varying_i8p calls is_defined_group, parse
get_cla_list_varying_logical calls is_defined_group, parse
get_cla_list_varying_r16p calls is_defined_group, parse
get_cla_list_varying_r4p calls is_defined_group, parse
get_cla_list_varying_r8p calls is_defined_group, parse
get_cla_list calls is_defined_group, parse
get_clasg_indexes calls is_defined_group
get_cla calls is_defined_group, parse
is_called_group calls is_defined_group
is_defined calls is_defined_group
is_passed calls is_defined_group
set_mutually_exclusive_groups calls is_defined_group
fake_call calls add_group, add, get, parse
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes
parse calls add, check_m_exclusive, check, is_defined, get_args
flap_save_bash_completion calls add_group, add, parse
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, is_passed, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, is_passed, get_varying, get, parse
flap_test_choices_logical calls add, get, parse
flap_test_duplicated_clas calls add, get
flap_test_group_examples calls add_group, add, is_called_group, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_nested calls add_group, add, is_called_group, set_mutually_exclusive_groups, get, parse
flap_test_string calls add, get, parse
flap_test_group calls fake_call