is_defined – FLAP
is_defined Function
20 statements
Source File
private function is_defined(self, switch, pos)
Check if a CLA has been defined.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(in) :: self
CLAsG data.
character(len=*), intent(in) :: switch
Switch name.
integer(kind=I4P), intent(out), optional :: pos
CLA position.
Return Value logical
Check if a CLA has been defined.
Called by
Source Code
  function is_defined(self, switch, pos)
  !< Check if a CLA has been defined.
  class(command_line_arguments_group), intent(in)  :: self       !< CLAsG data.
  character(*),                        intent(in)  :: switch     !< Switch name.
  integer(I4P), optional,              intent(out) :: pos        !< CLA position.
  logical                                          :: is_defined !< Check if a CLA has been defined.
  integer(I4P)                                     :: a          !< CLA counter.
  is_defined = .false.
  if (present(pos)) pos = 0
  if (self%Na>0) then
    do a=1, self%Na
      if (.not.self%cla(a)%is_positional) then
        if ((self%cla(a)%switch==switch).or.(self%cla(a)%switch_ab==switch)) then
          is_defined = .true.
          if (present(pos)) pos = a
          exit
        endif
      endif
    enddo
  endif
  endfunction is_defined
Call graph
check calls is_defined, check
is_defined calls is_defined
parse calls is_defined, add, parse, check
add calls check, add
fake_call calls parse, add, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls parse, add
flap_test_basic calls parse, add, get_varying, get
flap_test_choices_logical calls parse, add, get
flap_test_nested calls parse, add, get
flap_test_string calls parse, add, get
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_duplicated_clas calls add, get
flap_test_group calls fake_call
flap_test_group_examples calls add, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get