is_passed – FLAP
is_passed Function
22 statements
Source File
private pure function is_passed(self, switch, position)
Check if a CLA has been passed.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(in) :: self
CLAsG data.
character(len=*), intent(in), optional :: switch
Switch name.
integer(kind=I4P), intent(in), optional :: position
Position of positional CLA.
Return Value logical
Check if a CLA has been passed.
Called by
Source Code
  pure function is_passed(self, switch, position)
  !< Check if a CLA has been passed.
  class(command_line_arguments_group), intent(in) :: self      !< CLAsG data.
  character(*), optional,              intent(in) :: switch    !< Switch name.
  integer(I4P), optional,              intent(in) :: position  !< Position of positional CLA.
  logical                                         :: is_passed !< Check if a CLA has been passed.
  integer(I4P)                                    :: a         !< CLA counter.
  is_passed = .false.
  if (self%Na>0) then
    if (present(switch)) then
      do a=1, self%Na
        if (.not.self%cla(a)%is_positional) then
          if ((self%cla(a)%switch==switch).or.(self%cla(a)%switch_ab==switch)) then
            is_passed = self%cla(a)%is_passed
            exit
          endif
        endif
      enddo
    elseif (present(position)) then
      is_passed = self%cla(position)%is_passed
    endif
  endif
  endfunction is_passed
Call graph
check_m_exclusive calls is_passed
is_passed calls is_passed
parse calls check_m_exclusive, parse
flap_test_action_store calls is_passed, get_varying, get
flap_test_basic calls is_passed, parse, get_varying, get
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls parse
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get