is_required_passed – FLAP
is_required_passed Function
10 statements
Source File
private function is_required_passed(self, pref) result(is_ok)
Check if required CLA is passed.
Type Bound
command_line_argument
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Return Value logical
Check result.
Calls
Called by
Source Code
  function is_required_passed(self, pref) result(is_ok)
  !< Check if required CLA is passed.
  class(command_line_argument), intent(inout) :: self  !< CLA data.
  character(*), optional,       intent(in)    :: pref  !< Prefixing string.
  logical                                     :: is_ok !< Check result.
  is_ok = .true.
  if (((.not.self%is_passed).and.self%is_required).or.((.not.self%is_passed).and.(.not.allocated(self%def)))) then
    call self%errored(pref=pref, error=ERROR_MISSING_REQUIRED)
    is_ok = .false.
  endif
  endfunction is_required_passed
Call graph
is_required_passed calls errored, is_required_passed
errored calls print_error_message
get_cla calls is_required_passed, get, parse
get_cla_list calls is_required_passed, get, parse
get_cla_list_varying_char calls is_required_passed, get_varying, parse
get_cla_list_varying_i1p calls is_required_passed, get_varying, parse
get_cla_list_varying_i2p calls is_required_passed, get_varying, parse
get_cla_list_varying_i4p calls is_required_passed, get_varying, parse
get_cla_list_varying_i8p calls is_required_passed, get_varying, parse
get_cla_list_varying_logical calls is_required_passed, get_varying, parse
get_cla_list_varying_r16p calls is_required_passed, get_varying, parse
get_cla_list_varying_r4p calls is_required_passed, get_varying, parse
get_cla_list_varying_r8p calls is_required_passed, get_varying, parse
parse calls is_required_passed
fake_call calls parse, get
flap_save_bash_completion calls parse
flap_test_basic calls parse, get_varying, get
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get