print_usage – FLAP
print_usage Subroutine
5 statements
Source File
private subroutine print_usage(self, pref)
Print correct usage.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(in) :: self
CLI data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Source Code
  subroutine print_usage(self, pref)
  !< Print correct usage.
  class(command_line_interface), intent(in) :: self  !< CLI data.
  character(*), optional,        intent(in) :: pref  !< Prefixing string.
  write(self%usage_lun, '(A)') self%usage(pref=pref, g=0)
  endsubroutine print_usage
Call graph
print_usage calls usage
usage calls signature, usage, cton, colorize, replace_all, str
signature calls signature, cton, str, has_choices
colorize calls colorize_default
replace_all calls replace, wstrip
colorize_default calls color_index, style_index, upper