print_error_message – FLAP
print_error_message Subroutine
5 statements
Source File
private subroutine print_error_message(self)
Print meaningful error message to standard-error.
Type Bound
object
Arguments
Type Intent Optional Attributes Name
class(object), intent(in) :: self
Object data.
Called by
Source Code
  subroutine print_error_message(self)
  !< Print meaningful error message to standard-error.
  class(object), intent(in) :: self !< Object data.
  write(self%error_lun, '(A)') self%error_message
  write(self%error_lun, '(A)')
  endsubroutine print_error_message
Call graph
errored calls print_error_message
check_action_consistency calls errored
check_choices calls errored
check_envvar_consistency calls errored
check_list_size calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
check calls errored, check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, check
get_cla calls errored, check_choices, get_cla_from_buffer, is_required_passed, get, parse
get_cla_from_buffer calls errored
get_cla_list calls errored, get_cla_list_from_buffer, is_required_passed, get, parse
get_cla_list_from_buffer calls errored, check_choices
get_cla_list_varying_char calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i1p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i2p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_i8p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_logical calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r16p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r4p calls errored, check_list_size, is_required_passed, get_varying, parse
get_cla_list_varying_r8p calls errored, check_list_size, is_required_passed, get_varying, parse
is_required_passed calls errored, is_required_passed
is_required_val_passed calls errored
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
add calls check, add
check_m_exclusive calls raise_error_m_exclude
parse calls raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing, add, check_m_exclusive, check, is_required_passed, parse
fake_call calls get, add, parse
flap_save_man_page calls get, add
flap_save_usage_to_markdown calls get, add
flap_test_action_store calls get_varying, get, add
flap_test_ansi_color_style calls get, add
flap_test_basic calls get_varying, get, add, parse
flap_test_choices_logical calls get, add, parse
flap_test_duplicated_clas calls get, add
flap_test_group_examples calls get, add
flap_test_hidden calls get, add
flap_test_ignore_unknown_clas calls get, add
flap_test_minimal calls get, add
flap_test_nargs_insufficient calls get, add
flap_test_nested calls get, add, parse
flap_test_string calls get, add, parse
flap_save_bash_completion calls add, parse
flap_test_group calls fake_call