raise_error_m_exclude – FLAP
raise_error_m_exclude Subroutine
5 statements
Source File
private subroutine raise_error_m_exclude(self, pref)
Raise error mutually exclusive CLAs passed.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(inout) :: self
CLA data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Calls
Called by
Source Code
  subroutine raise_error_m_exclude(self, pref)
  !< Raise error mutually exclusive CLAs passed.
  class(command_line_arguments_group), intent(inout) :: self !< CLA data.
  character(*), optional,              intent(in)    :: pref !< Prefixing string.
  call self%errored(pref=pref, error=ERROR_M_EXCLUDE)
  endsubroutine raise_error_m_exclude
Call graph
raise_error_m_exclude calls errored
errored calls colorize, print_error_message, str
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
check_m_exclusive calls raise_error_m_exclude
parse calls check_m_exclusive
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls parse
flap_test_basic calls parse, get_varying, get
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_save_man_page calls get
flap_save_usage_to_markdown calls get
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get