replace – FLAP
replace Function
16 statements
Source File
public pure function replace(string, substring, restring) result(newstring)
Replace substring (only first occurrence) into a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
String to be modified.
character(len=*), intent(in) :: substring
Substring to be replaced.
character(len=*), intent(in) :: restring
String to be inserted.
Return Value character(len=:), allocatable
New modified string.
Called by
Source Code
  pure function replace(string, substring, restring) result(newstring)
  !< Replace substring (only first occurrence) into a string.
  character(len=*), intent(in)  :: string    !< String to be modified.
  character(len=*), intent(in)  :: substring !< Substring to be replaced.
  character(len=*), intent(in)  :: restring  !< String to be inserted.
  character(len=:), allocatable :: newstring !< New modified string.
  integer(I4P)                  :: pos       !< Position from which replace the substring.
  pos = index(string=string, substring=substring)
  newstring = string
  if (pos>0) then
    if (pos==1) then
      newstring = restring//string(len(substring)+1:)
    else
      newstring = string(1:pos-1)//restring//string(pos+len(substring):)
    endif
  endif
  endfunction replace
Call graph
replace_all calls replace
sanitize_defaults calls replace_all, sanitize_defaults
usage calls replace_all, usage
is_required_passed calls usage
parse calls sanitize_defaults, is_required_passed, parse, usage, save_usage_to_markdown
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
print_usage calls usage
save_man_page calls usage
save_usage_to_markdown calls usage
flap_save_bash_completion calls parse
flap_test_basic calls parse, save_man_page, get_varying, get
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_save_man_page calls save_man_page, get
flap_save_usage_to_markdown calls save_usage_to_markdown, get
flap_test_group calls fake_call
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get