set_examples – FLAP
set_examples Subroutine
8 statements
Source File
private subroutine set_examples(self, examples)
Set examples of correct usage.
Type Bound
object
Arguments
Type Intent Optional Attributes Name
class(object), intent(inout) :: self
Object data.
character(len=*), intent(in), optional :: examples(1:)
Examples of correct usage.
Called by
Source Code
  subroutine set_examples(self, examples)
  !< Set examples of correct usage.
  class(object),          intent(inout) :: self         !< Object data.
  character(*), optional, intent(in)    :: examples(1:) !< Examples of correct usage.
  if (present(examples)) then
#ifdef __GFORTRAN__
    allocate(self%examples(1:size(examples)))
#else
    allocate(character(len=len(examples(1))):: self%examples(1:size(examples))) ! does not work with gfortran 4.9.2
#endif
    self%examples = examples
  endif
  endsubroutine set_examples
Call graph
add_group calls set_examples
init calls set_examples
add calls add_group
fake_call calls add_group, init, add, parse, get
flap_save_bash_completion calls add_group, init, add, parse
flap_save_man_page calls init, add, get
flap_save_usage_to_markdown calls init, add, get
flap_test_action_store calls init, add, get_varying, get
flap_test_ansi_color_style calls init, add, get
flap_test_basic calls init, add, parse, get_varying, get
flap_test_choices_logical calls init, add, parse, get
flap_test_duplicated_clas calls init, add, get
flap_test_group_examples calls add_group, init, add, get
flap_test_hidden calls init, add, get
flap_test_ignore_unknown_clas calls init, add, get
flap_test_minimal calls init, add, get
flap_test_nargs_insufficient calls init, add, get
flap_test_nested calls add_group, init, add, parse, get
flap_test_string calls init, add, parse, get
parse calls add
flap_test_group calls fake_call
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse