signature – FLAP
signature Function
27 statements
Source File
private function signature(self, bash_completion)
Get signature.
Type Bound
command_line_interface
Arguments
Type Intent Optional Attributes Name
class(command_line_interface), intent(in) :: self
CLI data.
logical, intent(in), optional :: bash_completion
Return the signature for bash completion.
Return Value character(len=:), allocatable
Signature.
Calls
Called by
Source Code
  function signature(self, bash_completion)
  !< Get signature.
  class(command_line_interface), intent(in) :: self             !< CLI data.
  logical, optional,             intent(in) :: bash_completion  !< Return the signature for bash completion.
  logical                                   :: bash_completion_ !< Return the signature for bash completion, local variable.
  character(len=:), allocatable             :: signature        !< Signature.
  integer(I4P)                              :: g                !< Counter.
  bash_completion_ = .false. ; if (present(bash_completion)) bash_completion_ = bash_completion
  if (bash_completion_) then
    signature = signature//new_line('a')//'    COMPREPLY=( )'
    signature = signature//new_line('a')//'    COMPREPLY+=( $( compgen -W "'//&
                self%clasg(0)%signature(bash_completion=bash_completion, plain=.true.)//'" -- $cur ) )'
    if (size(self%clasg,dim=1)>1) then
      do g=1,size(self%clasg,dim=1)-1
        signature = signature//new_line('a')//'    COMPREPLY+=( $( compgen -W "'//self%clasg(g)%group//'" -- $cur ) )'
      enddo
    endif
  else
    signature = self%clasg(0)%signature()
    if (size(self%clasg,dim=1)>1) then
      signature = signature//' {'//self%clasg(1)%group
      do g=2,size(self%clasg,dim=1)-1
        signature = signature//','//self%clasg(g)%group
      enddo
      signature = signature//'} ...'
    endif
  endif
  endfunction signature
Call graph
signature calls signature, cton, has_choices, str
save_man_page calls signature, usage
save_usage_to_markdown calls signature, usage
usage calls signature
parse calls save_usage_to_markdown, usage
print_usage calls usage
flap_save_man_page calls save_man_page, get
flap_save_usage_to_markdown calls save_usage_to_markdown, get
flap_test_basic calls save_man_page, parse, get_varying, get
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls parse
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get