styles_samples – FLAP
styles_samples Subroutine
9 statements
Source File
public subroutine styles_samples()
Print to standard output all styles samples.
Arguments
None
Calls
Called by
Source Code
   subroutine styles_samples()
   !< Print to standard output all styles samples.
   integer(int32) :: s !< Counter.
   print '(A)', colorize('Styles samples', color_fg='red_intense')
   do s=1, size(STYLES, dim=2)
      print '(A)', '  colorize("'//STYLES(1, s)//'", style="'//STYLES(1, s)//'") => '//&
         colorize(STYLES(1, s), style=STYLES(1, s))//&
         ' code: '//colorize(trim(STYLES(2, s)), color_fg='magenta', style='inverse_on')
   enddo
   endsubroutine styles_samples
Call graph
styles_samples calls colorize
colorize calls colorize_default
colorize_default calls color_index, style_index, upper
face_test_basic calls styles_samples