upper_case – FLAP
upper_case Function
13 statements
Source File
public elemental function upper_case(string)
Convert the lower case characters of a string to upper case one.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
String to be converted.
Return Value character(len=len)
Converted string.
Called by
Source Code
  elemental function upper_case(string)
  !< Convert the lower case characters of a string to upper case one.
  character(len=*), intent(in) :: string                                        !< String to be converted.
  character(len=len(string))   :: upper_case                                    !< Converted string.
  integer                      :: n1                                            !< Characters counter.
  integer                      :: n2                                            !< Characters counter.
  character(len=26), parameter :: upper_alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' !< Upper case alphabet.
  character(len=26), parameter :: lower_alphabet = 'abcdefghijklmnopqrstuvwxyz' !< Lower case alphabet.
  upper_case = string
  do n1=1, len(string)
    n2 = index(lower_alphabet, string(n1:n1))
    if (n2>0) upper_case(n1:n1) = upper_alphabet(n2:n2)
  enddo
  endfunction upper_case
Call graph
add calls upper_case
fake_call calls add, parse, get
parse calls add
flap_save_bash_completion calls add, parse
flap_save_man_page calls add, get
flap_save_usage_to_markdown calls add, get
flap_test_action_store calls add, get_varying, get
flap_test_ansi_color_style calls add, get
flap_test_basic calls add, parse, get_varying, get
flap_test_choices_logical calls add, parse, get
flap_test_duplicated_clas calls add, get
flap_test_group_examples calls add, get
flap_test_hidden calls add, get
flap_test_ignore_unknown_clas calls add, get
flap_test_minimal calls add, get
flap_test_nargs_insufficient calls add, get
flap_test_nested calls add, parse, get
flap_test_string calls add, parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_test_group calls fake_call