upper – FLAP
upper Function
11 statements
Source File
private elemental function upper(string)
Return a string with all uppercase characters.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Input string.
Return Value character(len=len)
Upper case string.
Called by
Contents
Source Code
upper
Source Code
   elemental function upper(string)
   !< Return a string with all uppercase characters.
   character(len=*), intent(in) :: string !< Input string.
   character(len=len(string))   :: upper  !< Upper case string.
   integer                      :: n1     !< Characters counter.
   integer                      :: n2     !< Characters counter.
   upper = string
   do n1=1, len(string)
      n2 = index(LOWER_ALPHABET, string(n1:n1))
      if (n2>0) upper(n1:n1) = UPPER_ALPHABET(n2:n2)
   enddo
   endfunction upper
Call graph
colorize_ascii calls upper
colorize_ucs4 calls upper
colorize_default calls upper
colorize calls colorize_default
errored calls colorize
face_test_styles calls colorize
styles_samples calls colorize
face_test_colors calls colorize
colors_samples calls colorize
usage calls colorize
face_test_basic calls styles_samples, colors_samples