usage – FLAP
usage Function
35 statements
Source File
private function usage(self, pref, no_header, markdown)
Get correct CLAsG usage.
Type Bound
command_line_arguments_group
Arguments
Type Intent Optional Attributes Name
class(command_line_arguments_group), intent(in) :: self
CLAsG data.
character(len=*), intent(in), optional :: pref
Prefixing string.
logical, intent(in), optional :: no_header
Avoid insert header to usage.
logical, intent(in), optional :: markdown
Format things form markdown.
Return Value character(len=:), allocatable
Usage string.
Calls
Called by
Source Code
  function usage(self, pref, no_header, markdown)
  !< Get correct CLAsG usage.
  class(command_line_arguments_group), intent(in) :: self      !< CLAsG data.
  character(*), optional,              intent(in) :: pref      !< Prefixing string.
  logical,      optional,              intent(in) :: no_header !< Avoid insert header to usage.
  logical,      optional,              intent(in) :: markdown  !< Format things form markdown.
  character(len=:), allocatable                   :: usage     !< Usage string.
  integer(I4P)                                    :: a         !< Counters.
  character(len=:), allocatable                   :: prefd     !< Prefixing string.
  logical                                         :: markdownd !< Markdonw format, local variable.
  markdownd = .false. ; if (present(markdown)) markdownd = markdown
  prefd = '' ; if (present(pref)) prefd = pref
  usage = self%progname ; if (self%group/='') usage = self%progname//' '//self%group
  usage = prefd//self%help//' '//usage//self%signature()
  if (self%description/='') usage = usage//new_line('a')//new_line('a')//prefd//self%description
  if (present(no_header)) then
    if (no_header) usage = ''
  endif
  if (self%Na_required>0) then
    usage = usage//new_line('a')//new_line('a')//prefd//'Required switches:'
    if(markdownd)usage = usage//'  '
    do a=1, self%Na
      if (self%cla(a)%is_required.and.(.not.self%cla(a)%is_hidden)) usage = usage//new_line('a')//&
        self%cla(a)%usage(pref=prefd,markdown=markdownd)
    enddo
  endif
  if (self%Na_optional>0) then
    usage = usage//new_line('a')//new_line('a')//prefd//'Optional switches:'
    if(markdownd)usage = usage//'  '
    do a=1, self%Na
      if (.not.self%cla(a)%is_required.and.(.not.self%cla(a)%is_hidden)) usage = usage//new_line('a')//&
        self%cla(a)%usage(pref=prefd,markdown=markdownd)
    enddo
  endif
  endfunction usage
Call graph
usage calls signature, usage, cton, colorize, replace_all, str
signature calls signature, cton, str, has_choices
colorize calls colorize_default
replace_all calls replace, wstrip
colorize_default calls color_index, style_index, upper
is_required_passed calls usage
parse calls is_required_passed, usage, save_usage_to_markdown
print_usage calls usage
save_man_page calls usage
save_usage_to_markdown calls usage
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
flap_save_bash_completion calls parse
flap_save_man_page calls save_man_page, get
flap_save_usage_to_markdown calls save_usage_to_markdown, get
flap_test_basic calls parse, save_man_page, get_varying, get
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
flap_test_group calls fake_call
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get