wstrip – FLAP
wstrip Function
5 statements
Source File
public pure function wstrip(string) result(newstring)
Strip out leading and trailing white spaces from a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
String to be modified.
Return Value character(len=:), allocatable
New modified string.
Called by
Source Code
  pure function wstrip(string) result(newstring)
  !< Strip out leading and trailing white spaces from a string.
  character(len=*), intent(in)  :: string    !< String to be modified.
  character(len=:), allocatable :: newstring !< New modified string.
  allocate(newstring, source=trim(adjustl(string)))
  endfunction wstrip
Call graph
replace_all calls wstrip
sanitize_defaults calls wstrip, replace_all, sanitize_defaults
usage calls replace_all, usage
parse calls sanitize_defaults, parse, is_required_passed, usage, save_usage_to_markdown
fake_call calls parse, get
get_cla_list_varying_char calls parse
get_cla_list_varying_i1p calls parse
get_cla_list_varying_i2p calls parse
get_cla_list_varying_i4p calls parse
get_cla_list_varying_i8p calls parse
get_cla_list_varying_logical calls parse
get_cla_list_varying_r16p calls parse
get_cla_list_varying_r4p calls parse
get_cla_list_varying_r8p calls parse
get_cla_list calls parse
get_cla calls parse
is_required_passed calls usage
flap_save_bash_completion calls parse
flap_test_basic calls parse, get_varying, get, save_man_page
flap_test_choices_logical calls parse, get
flap_test_nested calls parse, get
flap_test_string calls parse, get
print_usage calls usage
save_man_page calls usage
save_usage_to_markdown calls usage
flap_test_group calls fake_call
flap_save_man_page calls get, save_man_page
flap_save_usage_to_markdown calls get, save_usage_to_markdown
flap_test_action_store calls get_varying, get
flap_test_ansi_color_style calls get
flap_test_duplicated_clas calls get
flap_test_group_examples calls get
flap_test_hidden calls get
flap_test_ignore_unknown_clas calls get
flap_test_minimal calls get
flap_test_nargs_insufficient calls get