colorize – FLAP
colorize Interface
3 statements
Source File
public interface colorize
Calls
Called by
Contents
Module Procedures
colorize_default
Module Procedures
private pure function colorize_default(string, color_fg, color_bg, style) result(colorized)
Colorize and stylize strings, DEFAULT kind.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Input string.
character(len=*), intent(in), optional :: color_fg
Foreground color definition.
character(len=*), intent(in), optional :: color_bg
Background color definition.
character(len=*), intent(in), optional :: style
Style definition.
Return Value character(len=:),allocatable
Colorized string.
Call graph
colorize calls colorize_default
colorize_default calls color_index, upper, style_index
errored calls colorize
colors_samples calls colorize
styles_samples calls colorize
usage calls colorize
face_test_colors calls colorize
face_test_styles calls colorize
face_test_basic calls colors_samples, styles_samples