.TH test_nested "1" "<DATE>" "version v2.1.5" "test_nested Manual"
.SH NAME
test_nested - manual page for test_nested version v2.1.5
.SH SYNOPSIS
.B test_nested
[--authors] [--help] [--markdown] [--version] {init,commit,tag} ...
.SH DESCRIPTION
Toy program for testing FLAP with nested commands
.SH OPTIONS


Optional switches:
  --authors, -a
      default value .false.
      Print authors names
  --help, -h
      Print this help message
  --markdown, -md
      Save this help message in a Markdown file
  --version, -v
      Print version

Commands:
  init
      fake init versioning
  commit
      fake commit changes to current branch
  tag
      fake tag current commit

For more detailed commands help try:
  test_nested init -h,--help
  test_nested commit -h,--help
  test_nested tag -h,--help
.SH EXAMPLES
.PP
.nf
.RS
test_nested
test_nested -h
test_nested init
test_nested commit -m "fix bug-1"
test_nested tag -a "v2.1.5"
.RE
.fi
.PP
.SH AUTHOR
Stefano Zaghi
.SH COPYRIGHT
MIT
