face_test_basic – FLAP
face_test_basic Program
6 statements
Source File
Uses
face
FACE test.
Calls
Contents
Source Code
face_test_basic
Source Code
program face_test_basic
!< FACE test.
use face
implicit none
call colors_samples
call styles_samples
endprogram face_test_basic
Call graph
face_test_basic calls colors_samples, styles_samples
colors_samples calls colorize
styles_samples calls colorize
colorize calls colorize_default
colorize_default calls color_index, style_index, upper