face_test_styles – FLAP
face_test_styles Program
12 statements
Source File
Uses
face
FACE test.
Calls
Source Code
program face_test_styles
!< FACE test.
use face
implicit none
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='bold_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='italics_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='underline_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='inverse_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='strikethrough_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='framed_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='encircled_on')
print '(A)', colorize('Hello', color_fg='red')//colorize(' World', color_fg='blue', style='overlined_on')
endprogram face_test_styles
Call graph
face_test_styles calls colorize
colorize calls colorize_default
colorize_default calls color_index, style_index, upper