flap_save_usage_to_markdown – FLAP
flap_save_usage_to_markdown Program
15 statements
Source File
Uses
penf
flap
Test save_usage_to_markdown method.
Calls
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
character(len=99) :: md
Markdown file name.
integer(kind=I4P) :: i
Integer input.
real(kind=R8P) :: r
Real input.
Source Code
program flap_save_usage_to_markdown
!< Test `save_usage_to_markdown` method.
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli !< Command Line Interface (CLI).
character(99)                :: md  !< Markdown file name.
integer(I4P)                 :: i   !< Integer input.
real(R8P)                    :: r   !< Real input.
call cli%init(progname='flap_save_usage_to_markdown',                 &
              version='1.1.2',                                        &
              authors='Batman and Robin',                             &
              license='GPL v3',                                       &
              description = 'FLAP test save man page',                &
              examples=['flap_save_usage_to_markdown                       ', &
                        'flap_save_usage_to_markdown -m test.md -i 4       ', &
                        'flap_save_usage_to_markdown 3.2 -m test.md        ', &
                        'flap_save_usage_to_markdown -1.5 -m test.md -i 102'])
call cli%add(switch='--md',      switch_ab='-m', help='markdown file name', required=.false., act='store', def='test.md')
call cli%add(switch='--integer', switch_ab='-i', help='a integer',          required=.false., act='store', def='2')
call cli%add(positional=.true.,position=1,       help='a positional real',  required=.false.,              def='1.0')
call cli%get(switch='-m',    val=md)
call cli%save_usage_to_markdown(markdown_file=trim(md))
endprogram flap_save_usage_to_markdown
Call graph
flap_save_usage_to_markdown calls get, add, init, save_usage_to_markdown
add calls add, add_group, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
save_usage_to_markdown calls signature, usage, strz
add_group calls assign_object, is_defined_group, set_examples
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, errored, is_defined, is_defined_group, check
get_cla_list calls is_defined_group, get, errored, parse, get_cla_list_from_buffer, is_required_passed, tokenize
get_cla calls is_defined_group, get, errored, parse, check_choices, get_cla_from_buffer, is_required_passed
signature calls signature, cton, has_choices, str
usage calls signature, usage, colorize, cton, replace_all, str
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
parse calls add, save_usage_to_markdown, usage, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
colorize calls colorize_default
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
is_defined calls is_defined_group, is_defined
is_required_passed calls usage, is_required_passed, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
check_choices calls errored, cton, tokenize, str
colorize_default calls color_index, style_index, upper
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls tokenize, get_clasg_indexes
get_cla_from_buffer calls errored, cton
get_cla_list_from_buffer calls errored, cton, check_choices, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
replace_all calls replace, wstrip
get_clasg_indexes calls is_defined_group