flap_test_nested – FLAP
flap_test_nested Program
40 statements
Source File
Uses
penf
flap
A testing program for FLAP, Fortran command Line Arguments Parser for poor people
Compile
See compile instructions.
Usage Compile
See usage instructions.
Calls
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
logical :: authors_print
Boolean value.
character(len=500) :: message
Message value.
integer(kind=I4P) :: error
Error trapping flag.
Source Code
program flap_test_nested
!< A testing program for FLAP, Fortran command Line Arguments Parser for poor people
!<
!<### Compile
!< See [compile instructions](https://github.com/szaghi/FLAP/wiki/Download-compile).
!<
!<###Usage Compile
!< See [usage instructions](https://github.com/szaghi/FLAP/wiki/Testing-Programs).
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli           !< Command Line Interface (CLI).
logical                      :: authors_print !< Boolean value.
character(500)               :: message       !< Message value.
integer(I4P)                 :: error         !< Error trapping flag.
authors_print = .false.
! initialize Command Line Interface
call cli%init(progname    = 'test_nested',                                       &
              version     = 'v2.1.5',                                            &
              authors     = 'Stefano Zaghi',                                     &
              license     = 'MIT',                                               &
              description = 'Toy program for testing FLAP with nested commands', &
              examples    = ['test_nested                      ',                &
                             'test_nested -h                   ',                &
                             'test_nested init                 ',                &
                             'test_nested commit -m "fix bug-1"',                &
                             'test_nested tag -a "v2.1.5"      '])
! set a Command Line Argument without a group to trigger authors names printing
call cli%add(switch='--authors',switch_ab='-a',help='Print authors names',required=.false.,act='store_true',def='.false.')
! set Command Line Arguments Groups, i.e. commands
call cli%add_group(group='init',description='fake init versioning')
call cli%add_group(group='commit',description='fake commit changes to current branch')
call cli%add_group(group='tag',description='fake tag current commit')
call cli%set_mutually_exclusive_groups(group1='init',group2='commit')
! set Command Line Arguments of commit command
call cli%add(group='commit',switch='--message',switch_ab='-m',help='Commit message',required=.false.,act='store',def='')
! set Command Line Arguments of commit command
call cli%add(group='tag',switch='--annotate',switch_ab='-a',help='Tag annotation',required=.false.,act='store',def='')
! parse Command Line Interface
call cli%parse(error=error)
if (error/=0) then
  print '(A)', 'Error code: '//trim(str(n=error))
  stop
endif
! use Command Line Interface data to trigger program behaviour
call cli%get(switch='-a',val=authors_print,error=error) ; if (error/=0) stop
if (authors_print) then
  print '(A)','Authors: '//cli%authors
elseif (cli%run_command('init')) then
  print '(A)','init (fake) versioning'
elseif (cli%run_command('commit')) then
  call cli%get(group='commit',switch='-m',val=message,error=error) ; if (error/=0) stop
  print '(A)','commit changes to current branch with message "'//trim(message)//'"'
elseif (cli%run_command('tag')) then
  call cli%get(group='tag',switch='-a',val=message,error=error) ; if (error/=0) stop
  print '(A)','tag current branch with message "'//trim(message)//'"'
else
  print '(A)','cowardly you are doing nothing... try at least "-h" option!'
endif
endprogram flap_test_nested
Call graph
flap_test_nested calls get, add_group, add, init, is_called_group, parse, set_mutually_exclusive_groups, str
add_group calls assign_object, is_defined_group, set_examples
add calls add_group, add, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
is_called_group calls is_defined_group
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
set_mutually_exclusive_groups calls is_defined_group
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, is_defined_group, check, is_defined, errored
get_cla_list calls parse, is_defined_group, get, errored, is_required_passed, tokenize, get_cla_list_from_buffer
get_cla calls parse, is_defined_group, get, errored, is_required_passed, check_choices, get_cla_from_buffer
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, str, cton, colorize, replace_all
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, str, cton, has_choices
colorize calls colorize_default
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
check_choices calls str, cton, errored, tokenize
colorize_default calls color_index, style_index, upper
get_cla_from_buffer calls cton, errored
get_cla_list_from_buffer calls cton, errored, tokenize, check_choices