flap_test_choices_logical – FLAP
flap_test_choices_logical Program
13 statements
Source File
Uses
penf
flap
Test FLAP for bad usage of choices option with logical
Calls
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
logical :: vbval
Valued-boolean value.
integer(kind=I4P) :: error
Error trapping flag.
Source Code
program flap_test_choices_logical
!< Test FLAP for bad usage of choices option with logical
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli   !< Command Line Interface (CLI).
logical                      :: vbval !< Valued-boolean value.
integer(I4P)                 :: error !< Error trapping flag.
call cli%init(progname='test_choices_logical')
call cli%add(switch='--boolean-value', switch_ab='-bv', help='A help message', &
             required=.false., def='.false.', choices='.True.,.False.', act='store', error=error)
call cli%parse(error=error)
call cli%get(switch='-bv', val=vbval, error=error)
print "(A)", "Error code: "//trim(str(error, .true.))
endprogram flap_test_choices_logical
Call graph
flap_test_choices_logical calls get, add, init, parse, str
add calls add, add_group, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
add_group calls assign_object, is_defined_group, set_examples
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, is_defined_group, check, is_defined, errored
get_cla_list calls parse, is_defined_group, get, errored, is_required_passed, tokenize, get_cla_list_from_buffer
get_cla calls parse, is_defined_group, get, errored, is_required_passed, check_choices, get_cla_from_buffer
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, str, cton, colorize, replace_all
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, str, cton, has_choices
colorize calls colorize_default
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
check_choices calls str, cton, errored, tokenize
colorize_default calls color_index, style_index, upper
get_cla_from_buffer calls cton, errored
get_cla_list_from_buffer calls cton, errored, tokenize, check_choices