flap_save_bash_completion – FLAP
flap_save_bash_completion Program
20 statements
Source File
Uses
penf
flap
Test save_bash_completion method.
Calls
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
character(len=37) :: bash_file = 'flap_test_save_bash_completion.bash'
Bash script file name.
Source Code
program flap_save_bash_completion
!< Test `save_bash_completion` method.
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli                                             !< Command Line Interface (CLI).
character(37)                :: bash_file='flap_test_save_bash_completion.bash' !< Bash script file name.
call cli%init(progname='flap_test_save_bash_completion')
call cli%add(switch_ab='-b',  required=.false., act='store', def='no', choices='yes,no')
call cli%add_group(group='compile', description='compile sources')
call cli%add_group(group='clean',   description='clean compiled objects')
call cli%add(group='compile', switch='--compiler',  switch_ab='-c',  required=.false., act='store',      def='gnu')
call cli%add(group='compile', switch='--flags',     switch_ab='-f',  required=.false., act='store',      def='-O2')
call cli%add(group='clean',   switch='--clean',     switch_ab='-c',  required=.false., act='store_true', def='.false.')
call cli%add(group='clean',   switch='--clean-all', switch_ab='-ca', required=.false., act='store_true', def='.false.')
call cli%add(group='compile', positional=.true., position=1,         required=.false.,                   def='1.0')
call cli%add(group='compile', switch='--integer',   switch_ab='-i',  required=.false., act='store',      def='1',   choices='1,3,5')
call cli%add(group='compile', switch='--real',                       required=.false., act='store',      def='1.0', choices='1.,2.')
call cli%parse
call cli%save_bash_completion(bash_file=trim(bash_file))
endprogram flap_save_bash_completion
Call graph
flap_save_bash_completion calls add_group, add, init, parse, save_bash_completion
add_group calls assign_object, is_defined_group, set_examples
add calls add_group, add, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
save_bash_completion calls signature
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, is_defined_group, check, is_defined, errored
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
signature calls signature, cton, has_choices, str
usage calls signature, usage, cton, replace_all, str, colorize
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
errored calls str, colorize, print_error_message
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
colorize calls colorize_default
colorize_default calls color_index, style_index, upper