flap_test_group – FLAP
flap_test_group Program
69 statements
Source File
Uses
tester
penf
flap
A testing program for FLAP, Fortran command Line Arguments Parser for poor people
Compile
See compile instructions.
Usage Compile
See usage instructions.
Calls
Variables
Type Attributes Name Initial
type(tester_t) :: crash_test_dummy
Tests handler.
logical :: switch_value_domain
Switch sentinel.
logical :: switch_value_grid
Switch sentinel.
logical :: switch_value_spectrum
Switch sentinel.
Subroutines
subroutine fake_call(args, spectrum, domain, grid)
Wrapper for fake calls.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: args
Fake arguments.
logical, intent(out) :: spectrum
Spectrum value.
logical, intent(out) :: domain
Domain value.
logical, intent(out) :: grid
Grid value.
Source Code
program flap_test_group
!< A testing program for FLAP, Fortran command Line Arguments Parser for poor people
!<
!<### Compile
!< See [compile instructions](https://github.com/szaghi/FLAP/wiki/Download-compile).
!<
!<###Usage Compile
!< See [usage instructions](https://github.com/szaghi/FLAP/wiki/Testing-Programs).
use flap, only : command_line_interface
use penf
use tester
implicit none
type(tester_t)               :: crash_test_dummy      !< Tests handler.
logical                      :: switch_value_domain   !< Switch sentinel.
logical                      :: switch_value_grid     !< Switch sentinel.
logical                      :: switch_value_spectrum !< Switch sentinel.
call crash_test_dummy%init
call fake_call(args='', spectrum=switch_value_spectrum, domain=switch_value_domain, grid=switch_value_grid)
print*, 'test_group'
print*, 'spectrum = ', switch_value_spectrum
print*, 'domain   = ', switch_value_domain
print*, 'grid     = ', switch_value_grid
call crash_test_dummy%assert_equal(switch_value_spectrum, .false.)
call crash_test_dummy%assert_equal(switch_value_domain, .false.)
call crash_test_dummy%assert_equal(switch_value_grid , .false.)
call fake_call(args='new -s', spectrum=switch_value_spectrum, domain=switch_value_domain, grid=switch_value_grid)
print*, 'test_group new -s'
print*, 'spectrum = ', switch_value_spectrum
print*, 'domain   = ', switch_value_domain
print*, 'grid     = ', switch_value_grid
call crash_test_dummy%assert_equal(switch_value_spectrum, .true.)
call crash_test_dummy%assert_equal(switch_value_domain, .false.)
call crash_test_dummy%assert_equal(switch_value_grid , .false.)
call fake_call(args='new -d', spectrum=switch_value_spectrum, domain=switch_value_domain, grid=switch_value_grid)
print*, 'test_group new -d'
print*, 'spectrum = ', switch_value_spectrum
print*, 'domain   = ', switch_value_domain
print*, 'grid     = ', switch_value_grid
call crash_test_dummy%assert_equal(switch_value_spectrum, .false.)
call crash_test_dummy%assert_equal(switch_value_domain, .true.)
call crash_test_dummy%assert_equal(switch_value_grid , .false.)
call fake_call(args='new -g', spectrum=switch_value_spectrum, domain=switch_value_domain, grid=switch_value_grid)
print*, 'test_group new -g'
print*, 'spectrum = ', switch_value_spectrum
print*, 'domain   = ', switch_value_domain
print*, 'grid     = ', switch_value_grid
call crash_test_dummy%assert_equal(switch_value_spectrum, .false.)
call crash_test_dummy%assert_equal(switch_value_domain, .false.)
call crash_test_dummy%assert_equal(switch_value_grid , .true.)
call crash_test_dummy%print
contains
  subroutine fake_call(args, spectrum, domain, grid)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Wrapper for fake calls.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in)     :: args     !< Fake arguments.
  logical,      intent(out)    :: spectrum !< Spectrum value.
  logical,      intent(out)    :: domain   !< Domain value.
  logical,      intent(out)    :: grid     !< Grid value.
  type(command_line_interface) :: cli      !< Command Line Interface (CLI).
  integer(I4P)                 :: error    !< Error trapping flag.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  call cli%init
  call cli%add_group(group='new', description='create new instance')
  call cli%add(group='new', switch='--spectrum', switch_ab='-s',            &
               help='Create new spectrum', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%add(group='new', switch='--domain', switch_ab='-d',            &
               help='Create new domain', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%add(group='new', switch='--grid', switch_ab='-g',            &
               help='Create new grid', required=.false., def='.false.', &
               act='store_true', error=error)
  if (error/=0) stop
  call cli%parse(args=args, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--spectrum', val=spectrum, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--domain', val=domain, error=error)
  if (error/=0) stop
  call cli%get(group='new', switch='--grid', val=grid, error=error)
  if (error/=0) stop
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine fake_call
endprogram flap_test_group
Call graph
flap_test_group calls assert_equal, fake_call, init
fake_call calls get, add_group, add, init, parse
add_group calls assign_object, is_defined_group, set_examples
add calls add_group, add, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, is_defined_group, check, is_defined, errored
get_cla_list calls parse, is_defined_group, get, errored, is_required_passed, tokenize, get_cla_list_from_buffer
get_cla calls parse, is_defined_group, get, errored, is_required_passed, check_choices, get_cla_from_buffer
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, cton, colorize, replace_all, str
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls get_clasg_indexes, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, cton, str, has_choices
colorize calls colorize_default
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace
check_choices calls cton, errored, tokenize, str
colorize_default calls color_index, style_index, upper
get_cla_from_buffer calls cton, errored
get_cla_list_from_buffer calls cton, errored, tokenize, check_choices