flap_test_hidden – FLAP
flap_test_hidden Program
27 statements
Source File
Uses
penf
flap
A testing program for FLAP, Fortran command Line Arguments Parser for poor people
Compile
See compile instructions.
Usage Compile
See usage instructions.
Calls
Variables
Type Attributes Name Initial
type(command_line_interface) :: cli
Command Line Interface (CLI).
character(len=99) :: a_string
String value.
character(len=99) :: g_string
Ghost string value.
integer(kind=I4P) :: a_integer
Integer value.
integer(kind=I4P) :: error
Error trapping flag.
Source Code
program flap_test_hidden
!< A testing program for FLAP, Fortran command Line Arguments Parser for poor people
!<
!<### Compile
!< See [compile instructions](https://github.com/szaghi/FLAP/wiki/Download-compile).
!<
!<###Usage Compile
!< See [usage instructions](https://github.com/szaghi/FLAP/wiki/Testing-Programs).
use flap, only : command_line_interface
use penf
implicit none
type(command_line_interface) :: cli       !< Command Line Interface (CLI).
character(99)                :: a_string  !< String value.
character(99)                :: g_string  !< Ghost string value.
integer(I4P)                 :: a_integer !< Integer value.
integer(I4P)                 :: error     !< Error trapping flag.
call cli%init(description = 'hiddens usage FLAP example')
call cli%add(switch='--string', switch_ab='-s', help='a string', required=.true., act='store', error=error) ; if (error/=0) stop
call cli%add(switch='--hidden', switch_ab='-hi', help='ghost string', required=.false., def='gstring not passed', &
             hidden=.true., act='store', error=error) ; if (error/=0) stop
call cli%add(switch='--integer', switch_ab='-i', help='a integer', required=.true., act='store', error=error) ; if (error/=0) stop
call cli%get(switch='-s', val=a_string, error=error) ; if (error/=0) stop
call cli%get(switch='-hi', val=g_string, error=error) ; if (error/=0) stop
call cli%get(switch='-i', val=a_integer, error=error) ; if (error/=0) stop
print '(A)', cli%progname//' has been called with the following argument:'
print '(A)', 'String       = '//trim(adjustl(a_string))
print '(A)', 'Ghost string = '//trim(adjustl(g_string))
print '(A)', 'Integer      = '//trim(adjustl(str(a_integer, .true.)))
endprogram flap_test_hidden
Call graph
flap_test_hidden calls get, add, init, str
add calls add, add_group, assign_object, check, is_defined_group, upper_case
init calls assign_object, set_examples
add_group calls assign_object, is_defined_group, set_examples
check calls check_action_consistency, check_envvar_consistency, check_m_exclude_consistency, check_named_consistency, check_optional_consistency, check_positional_consistency, errored, is_defined, is_defined_group, check
get_cla_list calls is_defined_group, get, errored, parse, get_cla_list_from_buffer, is_required_passed, tokenize
get_cla calls is_defined_group, get, errored, parse, check_choices, get_cla_from_buffer, is_required_passed
check_action_consistency calls errored
check_envvar_consistency calls errored
check_m_exclude_consistency calls errored
check_named_consistency calls errored
check_optional_consistency calls errored
check_positional_consistency calls errored
errored calls colorize, print_error_message, str
parse calls add, get_args, check_m_exclusive, check, is_defined, is_required_passed, parse, print_version, sanitize_defaults, save_usage_to_markdown, usage, assign_object, cton, raise_error_duplicated_clas, raise_error_nargs_insufficient, raise_error_switch_unknown, raise_error_value_missing
colorize calls colorize_default
check_m_exclusive calls is_defined_group, raise_error_m_exclude, is_passed
is_defined calls is_defined_group, is_defined
is_required_passed calls is_required_passed, usage, errored
sanitize_defaults calls sanitize_defaults, replace_all, unique, wstrip
save_usage_to_markdown calls usage, signature, strz
usage calls signature, usage, str, colorize, cton, replace_all
check_choices calls str, errored, cton, tokenize
colorize_default calls color_index, style_index, upper
get_args_from_invocation calls get_clasg_indexes
get_args_from_string calls tokenize, get_clasg_indexes
get_cla_from_buffer calls errored, cton
get_cla_list_from_buffer calls errored, cton, check_choices, tokenize
raise_error_duplicated_clas calls errored
raise_error_m_exclude calls errored
raise_error_nargs_insufficient calls errored
raise_error_switch_unknown calls errored
raise_error_value_missing calls errored
signature calls signature, str, cton, has_choices
get_clasg_indexes calls is_defined_group
replace_all calls wstrip, replace