tokenize – FLAP
tokenize Subroutine
Source File
Variables
strsub dlen c n t
Source Code
tokenize
All Procedures
add add_cla_clasg add_group assign_cla assign_clasg assign_cli assign_object called_group check check_choices_cla check_cla check_clasg check_list_size_cla check_m_exclusive check_m_exclusive_clasg check_required_clasg defined defined_clasg defined_group errored finalize finalize_cla finalize_clasg free free_cla free_clasg free_object get_args_from_invocation get_args_from_string get_cla get_cla_cli get_cla_list get_cla_list_cli get_cla_list_varying_char get_cla_list_varying_char_cli get_cla_list_varying_I1P get_cla_list_varying_I1P_cli get_cla_list_varying_I2P get_cla_list_varying_I2P_cli get_cla_list_varying_I4P get_cla_list_varying_I4P_cli get_cla_list_varying_I8P get_cla_list_varying_I8P_cli get_cla_list_varying_logical get_cla_list_varying_logical_cli get_cla_list_varying_R16P get_cla_list_varying_R16P_cli get_cla_list_varying_R4P get_cla_list_varying_R4P_cli get_cla_list_varying_R8P get_cla_list_varying_R8P_cli get_clasg_indexes init parse parse_clasg passed passed_clasg print_usage print_version save_man_page set_mutually_exclusive_groups signature signature_cla signature_clasg tokenize Upper_Case usage usage_cla usage_clasg
private puresubroutine tokenize(strin, delimiter, toks, Nt)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: strin
String to be tokenized.
character(len=*), intent(in) :: delimiter
Delimiter of tokens.
character(len=len(strin)), intent(out), allocatable :: toks(:)
Tokens.
integer(kind=I4P), intent(out), optional :: Nt
Number of tokens.
Description
Tokenize a string in order to parse it.
Note
The dummy array containing tokens must allocatable and its character elements must have the same length of the input string. If the length of the delimiter is higher than the input string one then the output tokens array is allocated with only one element set to char(0).
Called By
Variables
Type Visibility Attributes Name Initial
character(len=len(strin)), public :: strsub
Temporary string.
integer(kind=I4P), public :: dlen
Delimiter length.
integer(kind=I4P), public :: c
Counter.
integer(kind=I4P), public :: n
Counter.
integer(kind=I4P), public :: t
Counter.
Source Code
  pure subroutine tokenize(strin, delimiter, toks, Nt)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Tokenize a string in order to parse it.
  !<
  !< @note The dummy array containing tokens must allocatable and its character elements must have the same length of the input
  !< string. If the length of the delimiter is higher than the input string one then the output tokens array is allocated with
  !< only one element set to char(0).
  !---------------------------------------------------------------------------------------------------------------------------------
  character(len=*),          intent(IN)               :: strin     !< String to be tokenized.
  character(len=*),          intent(IN)               :: delimiter !< Delimiter of tokens.
  character(len=len(strin)), intent(OUT), allocatable :: toks(:)   !< Tokens.
  integer(I4P),              intent(OUT), optional    :: Nt        !< Number of tokens.
  character(len=len(strin))                           :: strsub    !< Temporary string.
  integer(I4P)                                        :: dlen      !< Delimiter length.
  integer(I4P)                                        :: c         !< Counter.
  integer(I4P)                                        :: n         !< Counter.
  integer(I4P)                                        :: t         !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  ! initialization
  if (allocated(toks)) deallocate(toks)
  strsub = strin
  dlen = len(delimiter)
  if (dlen>len(strin)) then
    allocate(toks(1:1)) ; toks(1) = char(0) ; if (present(Nt)) Nt = 1 ; return
  endif
  ! compute the number of tokens
  n = 1
  do c=1,len(strsub)-dlen ! loop over string characters
    if (strsub(c:c+dlen-1)==delimiter) n = n + 1
  enddo
  allocate(toks(1:n))
  ! tokenization
  do t=1,n ! loop over tokens
    c = index(strsub,delimiter)
    if (c>0) then
      toks(t) = strsub(1:c-1)
      strsub = strsub(c+dlen:)
    else
      toks(t) = strsub
    endif
  enddo
  if (present(Nt)) Nt = n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine tokenize
Call graph
get_cla_list_varying_i4p calls tokenize
get_cla_list calls tokenize
get_cla_list_varying_char calls tokenize
get_cla_list_varying_r16p calls tokenize
get_args_from_string calls tokenize, sanitize_args
get_cla_list_varying_i8p calls tokenize
get_cla_list_varying_i1p calls tokenize
check_choices_cla calls tokenize
get_cla_list_varying_logical calls tokenize
get_cla_list_varying_r4p calls tokenize
get_cla_list_varying_r8p calls tokenize
get_cla_list_varying_i2p calls tokenize